### PR TITLE
Allow guests to use of arsenal limits dialog and set default guest limit to 0

### LINKED ISSUE #3230: [Change]: Start default arsenal limits at 0
An idea I liked from a Discord suggestion: Instead of setting the default guest limits around the unlock limit, start them at zero. If commanders want to unlock an item or preserve some of it for member use, they can set the limit higher. Guest commanders would be allowed to increase guest limits to the unlock limit, but not reduce them.

The vast majority of gear found either will never be unlocked or isn't very useful to unlock, so given that few commanders use the limits dialog at the moment, this seems like a better approach for weapon variety. On the other hand, there would be a effective reduction in member privileges. Not sure how controversial that's going to be.

### PR DESCRIPTION
**Pull request by jaj22**
### What type of PR is this.
1. [ ] Bug
2. [X] Change
3. [ ] Enhancement

### What have you changed and why?
See #3230. Flipped the use of the arsenal limits dialog so that the default guest limit is 0 and commanders need to intentionally block removal of items from the arsenal. Enabled guest commanders to use the arsenal limits dialog to increase (but not decrease) limits, so that they can manage unlocking.

### Please specify which Issue this PR Resolves.
closes #3230

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

IIRC the arsenal limits dialog doesn't work correctly in all resolutions and UI size settings, so I may need to sort that out if use of the dialog becomes more critical.

### How can the changes be tested?
Make yourself a guest in localhost:
```
membersX = [];
membershipEnabled = true;
```

### CODE REVIEW

**Comment by jaj22** [comment]
Added save & load of arsenal limits data. Should have been there ages ago.

**Review by ante185 — APPROVED** [review]
lgtm imo

**Comment by jaj22** [comment]
- Ported arsenal limits dialog to Antistasi GUI style. 
- Changed logic to store last member-set value and constrain to that. Guests can now reduce guest-set values.

@ante185 Probably needs a second look.

**Comment by ante185** [comment]
Yep looks good still

**Pull request merged**
