### PR TITLE
Removed empty Hints and non-customHints.

### LINKED ISSUE #1608: Convert non-customHints to customHints.
Convert non-customHints to customHints.

### PR DESCRIPTION
**Pull request by CalebSerafin**
## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement/Refactor

### What have you changed and why?
Information:
* All empty hints have been removed
* All hints have been made into customHint (outside UPSMON, commsMP is fine.)

### Please specify which Issue this PR Resolves.
closes #1608 https://github.com/official-antistasi-community/A3-Antistasi/issues/1608

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in singleplayer?
2. [ ] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Needs quick test

### How can the changes be tested?
Steps: Copy past hints into the console, to try to trigger them naturally.

### CODE REVIEW

**Comment by Lazejun** [comment]
Since you are Touching it anyway,
you could also remove the Custom hint dependency in NavGrid Tools.

**Comment by CalebSerafin** [comment]
@Lazejun So if A3A_customHint does not exist, it uses vanilla hint? Or do you want me to delete the whole line?

**Comment by Lazejun** [comment]
Well it was never supposed to use the "Custom Hints", dont wanna blame or assume but i think Hazey littlery just searched the Whole project and slapped that on Vanilla Hints.

----> Yes Vanilla Hints, no dependencies Gang

**Comment by CalebSerafin** [comment]
see https://github.com/official-antistasi-community/A3-Antistasi/pull/1610

**Pull request closed without merging**
