### PR TITLE
Quality-of-life looting/logistics tweaks

### PR DESCRIPTION
**Pull request by jaj22**
### What type of PR is this.
1. [ ] Bug
2. [X] Change
3. [ ] Enhancement

### What have you changed and why?
Test PR for looting/logistics tweaks, intended to make the looting process less annoying without removing the time cost entirely.

- Switch loot crate carrying from forceWalk true to allowSprint false (about 2x faster movement).
- Enabled buying loot crates from any rebel flag.
- Fixed incorrect bounding box calc for load/unload.
- Changed load/unload speed to be independent of script load.

The bounding box calc change will have little effect for some vehicles (eg. vanilla offroad) but a huge effect for others (eg. vanilla HEMTT). Unloading a box from an HEMTT will no longer place it >5m behind the vehicle.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

I'll probably chuck it on the test server and see if anyone cares.

### CODE REVIEW

**Review by HakonRydland — APPROVED** [review]

**Comment by jaj22** [comment]
Hold this for a bit. Problem found in testing: It's too easy to accidentally (or otherwise) kill people with the loot crates when moving at jog speed. Probably need a workaround.

**Comment by killerswin2** [comment]
"Using attachTo with objects that have ragdoll physics (such as ammo boxes, containers, etc.) may cause unexpected behaviour. When you do so, if the attached object intersect origin object, origin object may gain some enormous collision properties even if the collision model for the attached object is not present localy to origin object, until detached. Vehicles may start flipping with no mass calculation (ie tank might fly), player object might gain infinite Z-vector velocity on any interaction with terrain relief and other objects."

**Comment by jaj22** [comment]
Ok, this isn't pretty but it works. The remoteExec setMass is weirdly far faster at propagating the mass change than waiting for the global effect. Without it, it's still easy to kill players with crates. ACE does the same thing.

**Comment by jaj22** [comment]
Oh yeah, the sleep is about right for allowing the crate to drop to the ground and become mostly harmless before it gets the mass bump.

**Review by killerswin2 — APPROVED** [review]
That looks good

**Pull request merged**
