### PR TITLE
Bug-fix Issue #1612 Roadblock/Outpost deploying state intermittently does not reflecting the truth

### LINKED ISSUE #1612: Roadblock/Observation Post deploying state intermittently does not reflecting the truth
**Describe the bug**
Commander -> Deploy O.Post / Roadblock fails with "We can only deploy / delete one Observation Post or Roadblock at a time" when there is none being deployed or deleting

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):

1. Deploy an roadblock
2. Have the roadblock squad be killed en-route
3. Try to deploy a new roadblock
4. See above message appear

**Expected behaviour**
Can always deploy a roadblock / O.Post if there is not one currently deploying

**Screenshots**
N/A

**Environment (please complete the following information):**
Version: 2.3.2 (also present in 2.3.1)
Map (specify if Altis Blufor): Altis

* [ ] LAN Hosted
* [ ] Private dedicated server
* [x] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset: CBA_A3, RHSUSAF, RHSAFRF, RHSGREF, Emhanced Movement, DUI - Squad Radar, VET_Unflipping
    
Time the bug occurred (Please leave in GMT+0): 01:20GMT
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: GMT

### PR DESCRIPTION
**Pull request by AlexTriada**
## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information: 
problem described in #1612
made some refactoring and more stable code

### Please specify which Issue this PR Resolves.
closes #1612

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in singleplayer?
2. [x] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

### CODE REVIEW

**Comment by Bob-Murphy** [comment]
Please add an issue containing more information about why a PR is needed, what the scope of the change/issue should be and link it to the pr.
Thank you.

**Comment by AlexTriada** [comment]
> Please add an issue containing more information about why a PR is needed, what the scope of the change/issue should be and link it to the pr.
> Thank you.

in the title

**Comment by jaj22** [comment]
So I read this through a couple of times and I can't see any functional differences. What am I missing?

**Comment by AlexTriada** [comment]
> What am I missing?

nothing

**Comment by AlexTriada** [comment]
this bug still present, but hard to repeat

**Pull request closed without merging**
