### PR TITLE
Fix for vehicle sell DS

### PR DESCRIPTION
**Pull request by Tiny-DM**
## What type of PR is this.
1. [X] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information: Fixes a bug where the garage sell would remove everyone's vehicle section on a dedicated server

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the mission in LAN host?
2. [X] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

### CODE REVIEW

**Review by jaj22 — CHANGES_REQUESTED** [review]
Needs a catIndex toggle in sellVehGRG so that selling statics works correctly.

**Comment by Tiny-DM** [comment]
Resolved now, tested on DS and LAN

**Review by jaj22 — APPROVED** [review]
Probably works, or at least it's less wrong than it was. Need to do some two player garage testing at some point though. Can't do it the usual way because the garage doesn't support loopback.

**Comment by Bob-Murphy** [comment]
Will be merged and pushed in 45 minutes. Can be checked on test server.

**Pull request merged**
