### PR TITLE
Aktualizovat řetězec stringtable.xml

### PR DESCRIPTION
**Pull request by MJVEVERUSKA**
Translation into Czech. Tested on the server. All right

### CODE REVIEW

**Comment by Bob-Murphy** [comment]
I will (hopefully) get somebody to cross check for mistakes. Nothing against you personally, just the 4-eye system we have.

**Comment by MJVEVERUSKA** [comment]
I understand. And I didn't do the translation for the first time, and where I sent them, they also did a cross-check, asking someone not to wait that long. Can you ask someone to cross-check?

**Comment by MJVEVERUSKA** [comment]
The point is, before the new version comes out, so that we can make it, thank you

**Comment by Bob-Murphy** [comment]
I already have two people working on it. In case it comes back positive it's very easy to implement it and we'll try to get it in before the release. I can't guarantee anything but we try.

**Comment by Bob-Murphy** [comment]
Hi MJVEVERUSKA,
in the attached file you can find the cross-checked translation.
When a change was suggested, they changed the line itself and added a comment what was changed to what.
Please go through the list and adapt your commit based on that. If you think that one of the changes they did is not matching, I leave it up to you to decide which one should be in the game.

Thank you!
[Czech check.txt](https://github.com/official-antistasi-community/A3-Antistasi/files/4740046/Czech.check.txt)

**Comment by MJVEVERUSKA** [comment]
Yes. I agree. Change in line 768  <Czech>Lov v lese</Czech>

**Comment by Bob-Murphy** [comment]
Please adjust your pull request with the changes and update it.
Thank you.

**Comment by Bob-Murphy** [comment]
Closed because #1080

**Pull request closed without merging**
