### PR TITLE
HC Mortar faction key fix

### PR DESCRIPTION
**Pull request by igorkis-scrts**
## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
HC mortar squads are not working due to faction hashmap key typo. This PR fixes that.     

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:

### CODE REVIEW

**Review by jaj22 — APPROVED** [review]
I suspect there are other bugs further down with mortar squads, but the fix here is straightforward.

**Comment by Bob-Murphy** [comment]
@jaj22 
We have more cases of `StaticMortar` instead of `staticMortar`.
What about those, can they stay or need adaptation a well?
image

**Comment by HakonRydland** [comment]
only the ones trying to get faction data, the ones left looks to all be isKindOf checks etc so no there fine

**Comment by jaj22** [comment]
@Bob-Murphy 
All of those are correct, as far as I can tell. There are two other uses of "StaticMortar": The old typeOfSoldier system (needs to die at some point) and isKindOf checks versus classnames. The casing is correct for those two.

**Comment by Bob-Murphy** [comment]
Thank you for checking.

**Pull request merged**
