### PR TITLE
Addition of WS parameter

### PR DESCRIPTION
**Pull request by RetardedFoX**
## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    Adds the Western Sahara DLC under parameters, with addition of `if allowDLCWS == True`:
    - Civilian clothing
    - Rebel clothing (the ION outfits)
    - Zamak (Flatbed + Cargo) to CSAT, LDF and AAF
    - Zu23 (Static + Truck) to AAF and Rebels
    - Marshall (ATGM + Command) to NATO
    Also includes the addition of Nyx (Autocannon & AT) for AAF `if allowDLCTanks == True`

### Please specify which Issue this PR Resolves.
closes none.

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

********************************************************

### CODE REVIEW

**Comment by Lazejun** [comment]
This will conflict with #2302 

Adding anything with the WS Parameter is pretty unsafe if there is no check if the CDLC is actually being loaded/Exists on the server.

**Comment by CalebSerafin** [comment]
It will need to work as a combination of installed DLC and mods. Where there is parameter switch and classname check.

**Comment by RetardedFoX** [comment]
> This will conflict with #2302

Will make it fit in when ^^ is merged.

**Review by Lazejun — APPROVED** [review]
Pushed some changes to stuff i found,
Looks pretty ok from my side, i would prefer if its merged after #2302 as there are a few more Templates, that are untouched by the changes in this one.

**Pull request merged**
