### PR TITLE
Refactor vehicle arsenal magazine selection, fix case sensitivity issue

### PR DESCRIPTION
**Pull request by jaj22**
## What type of PR is this.
1. [X] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Worked around an issue where RHS had the wrong casing for some magazine and magazineWell lists.

Refactored related code from two pass to single pass while attempting to find the problem.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

Was a relatively major change due to the refactor, so play around with the vehicle arsenal and check if I broke anything new.

### CODE REVIEW

**Review by Lazejun — APPROVED** [review]
Checked the previous case with the AK 105, it shows the Orange RPK Mags now.

Amount of Magazines shown Magazines seems to be equal to the normal Arsenal now.

**Comment by Bob-Murphy** [comment]
@jaj22 
Does this need more reviews or is it ready to merge?

**Comment by jaj22** [comment]
It's probably a waste of time inflicting a code review for the refactor part. It took me two hours staring at the original before I figured what it was trying to do. Given how long people spend in the arsenal, it should show up quickly on the test servers if anything is broken.

So yeah, two devs running the code and not tripping any problems should be sufficient.

**Comment by Bob-Murphy** [comment]
Good enough for me.

**Pull request merged**
