### PR TITLE
Fix some RHS flags

### PR DESCRIPTION
**Pull request by MadBender**
## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Proper NAPA flag is now used for NAPA instead of FIA flag

Flags markers on the map for CDF, NAPA and Serbia now have 3:2 proportions instead of being square and distorted.

I've added custom markers because RHS markers use wrong textures that look trimmed and/or distorted in game.

Before vs after:

image

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

Play a game with CDF, NAPA or Serbia and observe their flags on flag poles and on the map

### CODE REVIEW

**Comment by jaj22** [comment]
Looks reasonable except for the placement of the images. Do we really want a new data hierarchy four levels deep inside core? We already have a Pictures folder. Although why we have separate Sounds and Music folders with no distinction in usage is another matter...

What's the _ca stand for by the way?

**Comment by MadBender** [comment]
I didn't notice the `Pictures` folder and used the same path as the base game uses, e.g. `\A3\ui_f\data\map\markers\flags\nato_ca.paa`, assuming developers did their best organizing the resources and we can follow their patterns.

What do you recommend? If I shall use a different path, can you suggest which one? Probably should not dump these files straight inside `Pictures`

`_ca` means `Color with alpha`, I found this recommendation in the `ImageToPAA` tool

image

**Comment by jaj22** [comment]
> I didn't notice the Pictures folder and used the same path as the base game uses, e.g. \A3\ui_f\data\map\markers\flags\nato_ca.paa, assuming developers did their best organizing the resources and we can follow their patterns.

Fair enough, but I reckon one extra level on top of Pictures is enough considering that we're unlikely to ever go heavy on assets.  Maybe Pictures/flagmarkers, leaving organizational space for "flagtextures". Should probably get a second opinion from someone who likes organization. Maybe @Bob-Murphy.

**Review by Lazejun — APPROVED** [review]
Fine by me.

**Pull request merged**
