### PR TITLE
Disable lambs danger when it is loaded

### PR DESCRIPTION
**Pull request by diwako**
## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
This enhancement will disable lambs danger when it is loaded despite warnings to NOT load it.
It needs CBA, but that should be a requirement anyways already.

********************************************************
Notes:
I have gotten multiple people asking me about lambs and antistasi compat. Since lambs tries to integrate like vanilla AI, just with another FSM it is often seen that a mission should have an implementation to deal with it.
The Antistasi docs make it clear that lambs is not to be loaded and is not supported. As far as I could tell, it keeps happening that people do it anyways. So here ya go, it just disables all danger AI features from lambs without additional network cost. Problem solved.

### CODE REVIEW

**Review by HakonRydland — CHANGES_REQUESTED** [review]
we dont have nor will have a cba dependency, add a cba guard check

**Comment by diwako** [comment]
Can do

**Comment by HakonRydland** [comment]
also not you are not allowed to pull into master directly, but unstable instead, i already changed the target, you need to fix the one conflict within the workflow

**Comment by diwako** [comment]
There we go

**Comment by Bob-Murphy** [comment]
Thank you for the PR.
Less headaches for us and hopefully less questions for you.

**Comment by Bob-Murphy** [comment]
@HakonRydland I guess this is good now?

**Review by Bob-Murphy — APPROVED** [review]
lgtm

**Review by killerswin2 — APPROVED** [review]
This should be good for testing.

**Pull request merged**
