### PR TITLE
Fix error cases in crate generation, change from call to spawn

### PR DESCRIPTION
**Pull request by jaj22**
## What type of PR is this.
1. [X] Bug
2. [ ] Enhancement

### What have you changed and why?
Fixed one common and two unlikely cases where the crate loot generation code would error out due to accessing nil variables, blocking some crate items and possibly breaking the marker spawning.

Also switched the crate loot generation calls to spawn, as they're not time- or order-critical, and it protects the marker spawning code from other potential errors.

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

### CODE REVIEW

**Comment by CalebSerafin** [comment]
I'm not sure about changing calls to spawns. If code does not require to be in a schuduled it, it should not. Global variables can change mif execution. There is a time overhead for stopping and starting scripts. A solid execution order always means that unrelated scripts will not affect it. This means that a crate might exist for 3ms, the next 3ms it doesn't. Could i request that unless nessary calls stay calls. 

Handling nil and nulls is amazing work and something we need more of. When a nil is found could you please add that it logs it as it will help track down issues with other parts of the code.

**Comment by jaj22** [comment]
> I'm not sure about changing calls to spawns. If code does not require to be in a schuduled it, it should not. Global variables can change mif execution. There is a time overhead for stopping and starting scripts. A solid execution order always means that unrelated scripts will not affect it. This means that a crate might exist for 3ms, the next 3ms it doesn't. Could i request that unless nessary calls stay calls.

It's already scheduled. The garrison spawning functions here are all individually scheduled, and will even run on headless clients if available. Both examples you give (global variables changing or crates ceasing to exist during execution) are already possible.

The question is whether crate generation code should stall (and potentially block, on an error) the execution of garrison spawning code. As it has no real dependency, is demonstrably error-prone and difficult to test sufficiently due to heavy dependence on mods and game progression, I don't think it should.

**Comment by Spoffy** [comment]
I'm curious how _weaponLootWeighting could ever be nil. The only way I can see is if allX isn't initialised for every category, or if every gun in the game is unlocked. How did you get it to happen Jaj?

As for call Vs spawn, I think it's fine to spawn them in this case. NATOCrate is an expensive script, and only fires once, it doesn't stick around looping and wasting scheduler resources long term.

**Comment by jaj22** [comment]
> I'm curious how _weaponLootWeighting could ever be nil. The only way I can see is if allX isn't initialised for every category, or if every gun in the game is unlocked. How did you get it to happen Jaj?

I didn't, although my last vanilla run could have got to the point of unlocking every weapon. We went heavy on crates & ammo trucks early game, and vanilla has less stuff. I imagine it would be nearly impossible with RHS.

**Pull request merged**
