### PR TITLE
Terrains - Regero map port

### PR DESCRIPTION
**Pull request by killerswin2**
## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information: Added support for the Antistasi Mission on the Kingdom of Regero map by IceBreakr https://steamcommunity.com/sharedfiles/filedetails/?id=2278254320
Created regeroInfo.sqf for the antennas and Garrisons. Add Stringtable Entries for Regero.
Added Placeholder pictures for the port until better ones can be acquired. (<- that's for bob to get)
    
### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Needs to be loaded onto the test servers.
********************************************************
Notes:

### CODE REVIEW

**Comment by CalebSerafin** [comment]
Was the nav grid drawn manually or generated? For this map it needs to be drawn manually.

**Comment by killerswin2** [comment]
it was generated, then manually fixed for the problem areas

**Comment by killerswin2** [comment]
NavGrid is now manually drawn.

**Comment by killerswin2** [comment]
After testing and playing around on this map, the roads are god awful. They are so broken, no wonder street artist has issues with is map. I can't recommend that we port this map anymore. Closing this pr.

**Pull request closed without merging**
