### PR TITLE
Bug-fix Issue #1647 Artillery doesn't work well

### LINKED ISSUE #1647: Artillery doesn't work well
**Describe the bug**
Artillery (mortar team) doesn't work well, wrong rounds, errors, does not respond to commands, 0 rounds
and the mortar stops firing, even though one of the mortar crew is alive

**To Reproduce**
just to command mortar group

**Expected behaviour**
I expect the mortar units to give me the number of rounds I need, for example I give the command to fire 8 times, they should fire 8 times

**Environment (please complete the following information):**
Version:  2.3.2
Map (specify if Altis Blufor): all

* [x] LAN Hosted
* [x] Private dedicated server
* [x] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset:
RHS and Vanilla

### PR DESCRIPTION
**Pull request by AlexTriada**
## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information: 
When I playing commander role, I often using artillery, and I was constantly dissatisfied with how it works,
I give the command to shoot 8 rounds, and it shoots 3, for example, although the shells are available, then I
deсided rework this script, and this job is done in this PR
    
### Please specify which Issue this PR Resolves.
closes #1647

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in singleplayer?
2. [x] Have you loaded the mission in LAN host?
3. [x] Have you loaded the mission on a dedicated server? 

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)
still testing
### How can the changes be tested?
Steps: 

********************************************************
Notes:

### CODE REVIEW

**Comment by Bob-Murphy** [comment]
Hey Alex,
thanks for the PR.
We currently already have some PRs open with more strings and also new russian translations.
We need to check them first.
Could you maybe help us checking the russian translation?
I'm talking about the PRs #1589 and #1600 .

**Comment by AlexTriada** [comment]
Hi, Bob,
of course, I will help)

**Comment by Bob-Murphy** [comment]
Do I see it correctly that this is only about the artillery support that you can request by your friendly AI?

**Comment by AlexTriada** [comment]
Yes, it is

**Comment by Bob-Murphy** [comment]
Good to know, cheers.
Just to have it said again, it can take a while for that to be properly looked at as we are currently working on a bunch of stuff. So no worries.

**Comment by AlexTriada** [comment]
no problem, i already use it on my server, just decided to share

**Comment by jaj22** [comment]
> hard to describe, arty support was not working wright

So is this a bugfix+refactor rather than a feature? Original code didn't work correctly in some cases?

**Comment by AlexTriada** [comment]
> > hard to describe, arty support was not working wright
> 
> So is this a bugfix+refactor rather than a feature? Original code didn't work correctly in some cases?

exactly! original code didn't work correctly, in all cases, i am using arty every time and every time this is unpredictably count of fire, and fire at all.

**Comment by Bob-Murphy** [comment]
Please add an issue containing more information about why a PR is needed, what the scope of the change/issue should be and link it to the pr.
Thank you.

**Comment by AlexTriada** [comment]
> Please add an issue containing more information about why a PR is needed, what the scope of the change/issue should be and link it to the pr.
> Thank you.

done

**Comment by AlexTriada** [comment]
artillery now works as it should, stably and reliably

**Comment by AlexTriada** [comment]
I remembered that now in the mission, the commander can hire not only a mortar crew, but also a mortar squad, I need to check how the mortar squad works, what files it uses

**Comment by Bob-Murphy** [comment]
delayed because no workpower available to review

**Pull request closed without merging**
