### PR TITLE
Fix for minor header bug

### LINKED ISSUE #3050: [Bug]: Aborting Outpost Capture has missing title
### Describe the bug

Trying to take a flag and then using the "Abort Outpost Capture" action produces a hint with a missing title, as seen in this screenshot.

### How to reproduce

1. Load a vanilla Antistasi game
2. Find a flag to take and take it
3. While in the animation, use the scroll wheel option "Aborted Outpost Capture"

### Version

3.4.0

### Have you altered the code?

No

### What i have changed

_No response_

### Map

Altis

### What server?

LAN Hosted

### Time bug occured (Server time/UTC)

n/A

### Mods

```html
CBA_A3
Antistasi - The Mod
Zeus Enhanced
```

### Additional context

I freely acknowledge that I'm a bad person

### PR DESCRIPTION
**Pull request by Tiny-DM**
## What type of PR is this.
1. [X] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
the variable for the title was a private variable, so the hint actually calls the stringtable
decreased the time to wait to match a bit closer with when the animation is finished

### Please specify which Issue this PR Resolves.
closes #3050 

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

### CODE REVIEW

**Comment by Bob-Murphy** [comment]
If you check line 24, this private variable is done so you don't have to put the `localize .....` in every hint title when all hints have the same title.
It also works for all the other instances (this is used in 56 different files) so there must be a different reason.

**Comment by Tiny-DM** [comment]
Unfortunately, I don't have the intelligence to know why exactly, but this is what fixed it. My assumption is because the variable is nested inside an action and doesn't have access, because otherwise it should be fine

**Comment by jaj22** [comment]
The fix is correct. The reason is that it's used in an addAction here, so it's accessed in a completely different scope from where the local variable is defined. Event handlers are similar.

This isn't the only case where pulling out _titleStr breaks. There's a similar issue in the towing code. Maybe others.

**Review by jaj22 — APPROVED** [review]

**Comment by Bob-Murphy** [comment]
Could you please fix similar issues in the following files and give the PR a title change?
Thank you

- core\Scripts\fn_advancedTowingInit.sqf
- core\functions\REINF\fn_controlHCsquad.sqf
- core\functions\REINF\fn_controlunit.sqf

**Comment by Tiny-DM** [comment]
Forcing me to do the most basic shit....
done and tested @Bob-Murphy

**Review by jaj22 — APPROVED** [review]

**Pull request merged**
