### PR TITLE
block adding of action to pvp

### LINKED ISSUE #1512: PVP can use JNL load action
**Describe the bug**
Due to changes in the allowed pvp vehicles it is now possible for pvp players to load and run off with the crates located at seaports, outpost and airports.

**To Reproduce**
Play as pvp go to a spawned in outpost/seaport/airport, grab the crate and drive off

**Expected behaviour**
to not be able to steal the crate

**Screenshots**
N/A

**Environment (please complete the following information):**
Version: 2.3.1
Map (specify if Altis Blufor): 

[x] All the bellow
[ ] LAN Hosted
[ ] Private dedicated server
[ ] Private dedicated server with Headless client(s)
[ ] Community Server 1
[ ] Community Server 2
[ ] Community Test Server
[ ] Community Test Server 2

Modset: RHS has the pvp vehicle, all modsets can load them into vehicles
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

### PR DESCRIPTION
**Pull request by HakonRydland**
## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information: Stopped pvp players from getting the load action added
    

### Please specify which Issue this PR Resolves.
closes #1512

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in singleplayer?
2. [ ] Have you loaded the mission in LAN host?
3. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: Try to load a crate as pvp, you wont have the action, rebels will still have it

********************************************************
Notes:

### CODE REVIEW

**Review by CalebSerafin — APPROVED** [review]
Looks good,

**Comment by jaj22** [comment]
Sooooo...
- This function gets JIP'd, and according to its comments, this can happen before JNL init on clients.
- initClient stalls until the player unit is valid *after* running JNL init.
- The new code assumes that the player unit is valid.

At least one of these things is wrong. I'm not sure which yet as Arma documentation fails again. Installing the action for everyone and checking for pvp status in the action criteria would be safer, although I'm not sure if it's necessary.

**Review by jaj22 — CHANGES_REQUESTED** [review]
Tested with local DS:

- JIP remoteExecs can and routinely do execute before initClient.
- In every case I tried, the player unit was both valid and local by the time the remoteExec was executed.
- Multiple editors state in https://community.bistudio.com/wiki/player that the player unit isn't necessarily valid and local at this point. However, all mentions are quite old, so this may have been changed.

I would recommend not merging this PR until there's either a confirmation that Arma fixed the player unit init order, or some safety code is added (`waitUntil { !isNull player }` for example).

**Comment by HakonRydland** [comment]
> Tested with local DS:
> 
> * JIP remoteExecs can and routinely do execute before initClient.
> * In every case I tried, the player unit was both valid and local by the time the remoteExec was executed.
> * Multiple editors state in https://community.bistudio.com/wiki/player that the player unit isn't necessarily valid and local at this point. However, all mentions are quite old, so this may have been changed.
> 
> I would recommend not merging this PR until there's either a confirmation that Arma fixed the player unit init order, or some safety code is added (`waitUntil { !isNull player }` for example).

the safety code is probably the only reasonable thing, as i belive confirming it is fixed would require a lot of effort

**Review by jaj22 — APPROVED** [review]
Fair enough.

**Pull request merged**
