### PR TITLE
Additional TFAR Bags

### LINKED ISSUE #3405: [Change Request]: Add more TFAR backpacks to the starting gear
### Is the requested change related to a problem?

The current starting radio backpacks are very heavy. Forcing squad leads to carry more weight. In certain mod sets (3CB mods) you can find better LR backpacks (more capacity, less weight) but not all.

### Describe the solution you'd like.

Add the smaller TFAR backpacks to the initial rebel gear. Specifically the TFAR_rt1523g. It has much less capacity compared to the backpacks currently given, so there would be a tradeoff.

### Alternative solutions

There are a few other backpack types added by TFAR, one of each might be nice

### Additional context

Mostly relevant to the community servers where squad leaders are required to carry LR radios

### PR DESCRIPTION
**Pull request by Play3rgg**
Adds some indfor bags

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
Added more radio backpacks (TFAR Beta) to rebel factions.
Config Fixes for several backpacks
- give tfar capability to CWR3/CUP Kombat Radio and similar
- Added a3a_ versions of backpacks to give them INDFOR radio codes

Template changes only on REBEL templates.
We could give more templates SLs with radio backpacks - but that'd be another PR probably
    

### Please specify which Issue this PR Resolves.
closes #3405

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Play on Test Servers to possibly catch edge cases?
********************************************************
Notes:

### CODE REVIEW

**Comment by Play3rgg** [comment]
I need to remove this ANZAC one :P

**Comment by Play3rgg** [comment]
Probably shouldnt give the vanilla radio bags to CW factions etc...

**Comment by Play3rgg** [comment]
It is now ready :))

**Review by ante185 — APPROVED** [review]
Template changes seem to be fine and reasonable, some of the LR packs are just plain worse than the ones we already give the rebels, but the smaller lighter one are surely going to be appreciated.

@jaj22 Are you able to 2nd opinion the configs?

**Comment by jaj22** [comment]
I'm not that strong on TFAR config but everything looks technically correct. However, I'd lose the `mods` folder level (what else is going to be in there?). Don't feel like it needs to split out CfgVehicles from the config.cpps here either, but that probably looks like a convention at this point.

**Comment by jaj22** [comment]
Also you have some very mixed tab/space, sometimes within the same file. It's very obvious if you flick through the diff.

**Pull request merged**
