### PR TITLE
no unlocks without factory

### PR DESCRIPTION
**Pull request by killerswin2**
## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    Made it to no unlocks without a factory

### Please specify which Issue this PR Resolves.
closes Mini's Sanity

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

### CODE REVIEW

**Comment by Bob-Murphy** [comment]
This commit will not be merged without a proper conversation as it drastically changes a long implemented functionality and can significantly increase the difficulty for single players as well as small groups.

**Comment by killerswin2** [comment]
Absolutely, we will discuss this internally in our next dev meeting.

**Comment by killerswin2** [comment]
Bad Idea

**Comment by CalebSerafin** [comment]
Binary allow or disallow unlocks with factor is a little gimmicky.

If a rebel takes a single factory early game, then it makes no difference to gameplay impact compared to how it works now. 

If a rebal has no easy factories, then they will be restricted from unlocks for a long time.

**Pull request closed without merging**
