### PR TITLE
Updated AntistasiBulder to release build

### PR DESCRIPTION
**Pull request by HakonRydland**
## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    Rebuild the bu***i***lder to release version, this should solve the issues some individuals were having with using it.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

### CODE REVIEW

**Review by killerswin2 — APPROVED** [review]
Tested and works, ready for merge

**Review by Bob-Murphy — CHANGES_REQUESTED** [review]
Please correct the typo in the name

**Review by killerswin2 — APPROVED** [review]
builder spelling correct.

**Review by Bob-Murphy — APPROVED** [review]

**Comment by killerswin2** [comment]
> Where can I find the source code of "AntistasiBuilder.exe"?
 It was never released, and we don't really maintain it anymore. I might have a tar archive of it but I'll need to ask Hakon if we can release it.

**Pull request merged**
