### PR TITLE
Set Temperate as Default for Auto Selction.

### PR DESCRIPTION
**Pull request by Lazejun**
## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
As Temperate would work better for Arctic/Tropical than Arid it should be used as Default camo.

Renamed/Deleted Templates that had no need for a _camo as it only provides one variant with the given Equipment.

As Rebell Templates don't realy benefit from _camo variants that was scrapped too.

Gave Rebell Templates both variants of the TFAR Starting Radio as they are the same just a different color.

Changed the Special "Camo Case" for 3CB Civs to their Civ Faction names.

CHC will always be used, TKC only on "Middle Eastern" Maps as that seems more appropiate than always Arid Maps.

CMN will always be used, TKM only on "Middle Eastern" Maps as that seems more appropiate than always Arid Maps.

Until we get a Selection UI, Auto Selction will use Middle Eastern Rebells and Civs on Middle Eastern-ish Maps.

Fixed an Error in Selction for 3CB Factions as it would look for 3CB_AI_US_Marines and 3CB_AI_AFRF instead of RHS_AI....

Swapped a few Factions around for 3CB Factions to "Refresh it a little".

### Please specify which Issue this PR Resolves.
closes nothing

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Loading Maps with the Requiered Mods, it should not Lock up the Mission by selecting a Template that does not Exist,
It should load a Temperate Template if no Tropical/Arctic Template is given, instead of Arid.
********************************************************
Notes:

### CODE REVIEW

**Comment by killerswin2** [comment]
Go ahead and rename CSAT_Enoch to CSAT_Temperate

**Review by killerswin2 — APPROVED** [review]
looks good, other than my comment 
 suggestion good to merge.

**Comment by Lazejun** [comment]
> Go ahead and rename CSAT_Enoch to CSAT_Temperate

its _enoch as its intended for Livonia Only, we need to make a DLC Free variant but in general CSAT only offers Brown Hex and Green Hex + do a little DIsco dance with Auto Selection so Enoch is.

Same with Nato Tropical and CSAT Tropical.

Since we don't want to restrict people from Playing.

**Comment by Lazejun** [comment]
I will do a Seperate PR for the Vanilla DLC stuff to avoid throwing Watermarks and Equipment that at Players that they cannot use.

**Pull request merged**
