### PR TITLE
[Finished] Function lib rework, fully worked

### PR DESCRIPTION
**Pull request by AlexTriada**

### CODE REVIEW

**Comment by AlexTriada** [comment]
not working now, finding errors)

**Comment by Bob-Murphy** [comment]
@AlexTriada Just as an information for you, I opened an issue to tell you that you can start with the russian translation. If you have any questions about it please just post them in the issue number #228

**Comment by Spoffy** [comment]
Dude - this is *huge*. Can you split this pull request into several smaller pull requests?

276 file changes would take an insane amount of time to review.

**Comment by AlexTriada** [comment]
doesn't work yet, enemy bots won't spawn

**Comment by AlexTriada** [comment]
@Spoffy seems to have to break, and test at each stage, until I find what the problem is

**Comment by AlexTriada** [comment]
i found the error with file distances5.sqf linked to function distances4 that was my problem, i use distances4.sqf for function distances4 how could i be so stupid? everyone knows this!

**Comment by Spoffy** [comment]
I'll look into whether this should be merged after the latest bug fixes. First impressions of the code are good though.

**Comment by AlexTriada** [comment]
merge it)

**Comment by Spoffy** [comment]
After Wurzel's PR gets merged - trying to minimise breakages

**Comment by Spoffy** [comment]
Closing as merged. It'll be pushed to unstable soon.

**Pull request closed without merging**
