### PR TITLE
formatted changelog

### PR DESCRIPTION
**Pull request by Giddius**
## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
- formatted the changelog.txt roughly for ReStructuredText
- formatted the 2 newest Versions nicely.
> I did not format the rest nicely because they all have extremely different syntaxes (each and every version has a different one) and the cost/benefit just is not there to do this work, as most people won't actually look at the old versions anyway.

- changed file extension to `.rst` so github can somewhat render it.
> It is not perfect, but we can always point to the website for people wanting to read the changelog. 

### Please specify which Issue this PR Resolves.
None

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?
3. [x] not applicable

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
- look at the file in Github.

********************************************************
Notes:

- If wanted I can write a little style guide on how new entries to the changelog shall be written.

### CODE REVIEW

**Comment by Bob-Murphy** [comment]
Could you make it that the `:issue:` part is not visible?
image

**Comment by Bob-Murphy** [comment]
Also, the readme.rst can be viewed here:
https://github.com/official-antistasi-community/A3-Antistasi/blob/changelog_to_rst_retry/changelog.rst

**Comment by Giddius** [comment]
> 

Sadly not as, this is using an extension of sphinx to autolink the issue, this is the trade-off, but we can always refere people to the website for a pretty view

**Comment by CalebSerafin** [comment]
Seems okay. I'll give it a bit more time to see if anyone has any comments or suggestions.

**Comment by Giddius** [comment]
> Also, the readme.rst can be viewed here: https://github.com/official-antistasi-community/A3-Antistasi/blob/changelog_to_rst_retry/changelog.rst

how it currently looks rendered
Screenshot 2022-05-29 at 15-58-51 Changelog — Antistasi Guide documentation

**Comment by Giddius** [comment]
render with new change applied:
Screenshot 2022-05-29 at 16-20-35 Changelog — Antistasi Guide documentation

**Review by Bob-Murphy — APPROVED** [review]

**Pull request merged**
