### PR TITLE
fix invalid _baseSide variable check in undercover.sqf

### PR DESCRIPTION
**Pull request by AlexTriada**
No such variable: _baseSide

### CODE REVIEW

**Comment by Toakan** [comment]
Looks to fix the non-breaking cover for players raiding the Airport outside of detection zone.

LGTM

**Comment by AlexTriada** [comment]
I didn’t understand anything, but actually it’s not necessary, this variable is not declared, everything is simple

**Comment by AlexTriada** [comment]
guys, I honestly don’t understand why it’s not merged yet

**Comment by Toakan** [comment]
@AlexTriada, we are currently reviewing the Unstable branch for full Release. At this time the code base is frozen whilst we fix new bugs introduced.

**Pull request merged**
