### PR TITLE
Role description

### LINKED ISSUE #649: PvP Role Descriptions
@Lazejun 
image

### PR DESCRIPTION
**Pull request by Lazejun**
## What type of PR is this.
1. [ ] Bug
2. [X] Enhancement

### What have you changed and why?
Information:
Added Role description to all PVP Slots.
Slot 1 = Teamleader
Slot 2 = Medic
Slots 3 = Machinegunner
Slot 4 = Marksman
Slot 5 = AT1
Slots 6 = AT2

To make it easier to see which slot is which (was only a Problem on Recon Scout AT).

### Please specify which Issue this PR Resolves.
closes #649

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the Mission in Singleplayer?
2. [ ] Have you loaded the Mission in a Dedicated Server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

********************************************************
Notes:
In Theroy it would have been 120 Lines added but for some Reason there are a few more changes, which allready happend on Opening.
Chernarus Summer is a Mess.

### CODE REVIEW

**Comment by Bob-Murphy** [comment]
@Lazejun You gave at least some medics the "teamleader" description. Please fix.
Have not checked all files.

**Comment by Lazejun** [comment]
woopsie xD

**Comment by Bob-Murphy** [comment]
Now please give your commits proper names and then it should be good.
The name ideally should resemble what you have done in the commit,
I by now have checked all descriptions and that was the only mistake I found

**Comment by Bob-Murphy** [comment]
Ready for merging

**Comment by Bob-Murphy** [comment]
@Spoffy 
This is cleared for merging.

**Comment by Spoffy** [comment]
Manually merged in 139a3f6154340899ef2494d915fc8ba60d5ba23b

**Pull request closed without merging**
