### PR TITLE
Improve getArtilleryRanges, fix IFA mortar case

### LINKED ISSUE #3263: [Bug]: Artilllery minimum ranges are wrong
Couldn't figure out what the elevation numbers are relative to. Need that for the minimum.

Also apparently the IFA mortars have the wrong maximum range. Need to investigate.

### PR DESCRIPTION
**Pull request by jaj22**
## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?

- Improve artillery turret detection. I think they worked anyway with the fallback method, but this should throw fewer errors.
- Search fire modes properly in case the maximum charge size isn't 1. Apparently this was an issue with the IFA mortars.
- Remove incorrect attempt at determining minimum range. maxElev and minElev aren't easily usable because they seem to be relative to the default position in the model, which can't be obtained easily through code. Not worth the trouble so I set fixed minimums instead. Arty one might need a bump.

### Please specify which Issue this PR Resolves.
closes #3263

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

Should probably recheck some CUP/RHS/3CB artillery. I only did vanilla and IFA, although the methods should work everywhere.

### How can the changes be tested?
Spawn artillery unit as zeus. Enter as gunner and check the ranges in the artillery computer. Run this and compare the max range. Should be pretty close (note intentional 100m margin):
`[typeof vehicle player, magazines vehicle player # 0] call A3A_fnc_getArtilleryRanges`

### CODE REVIEW

**Comment by ante185** [comment]
Something funky happens with the LIB_M2_60 from IFA, it doesn't seems to happen anything else.
Max reported range from the artillery computer is 1945
A3A_fnc_getArtilleryRanges reports 1953

Statistically not likely to be a problem but i'd like to it

**Comment by jaj22** [comment]
> Something funky happens with the LIB_M2_60 from IFA, it doesn't seems to happen anything else. Max reported range from the artillery computer is 1945 A3A_fnc_getArtilleryRanges reports 1953

That would happen if the elevation of the turret doesn't actually go down to 45 degrees, and so the true maximum range is slightly shorter. Same problem as the true minimum range. Don't have a reasonable solution for it because there's no config or script function that tells you the initial elevation.

Could possibly workaround by changing minElev for that weapon so that the artillery computer max range adjusts to match...

**Comment by jaj22** [comment]
Ok fuck it, I replicated the artillery computer results. Witness the horror.

**Review by ante185 — APPROVED** [review]
tested all of IFA and vanilla artillery and it seems to correspond correctly
which is to say Looks Good To Me

**Pull request merged**
