### PR TITLE
Feature/mission dealer

### PR DESCRIPTION
**Pull request by JohnnyDeeee**
## What type of PR is this.
1. [ ] Bug
2. [x] Enhancement

### What have you changed and why?
Information:
Added the "Crazy irishman" mission from the original Antistasi.
(a big part is based on the original code for this mission, though i'm not sure which Antistasi version that is, i had a old mission file on my pc)
**Features**
- New mission type "FND" (short for Find)
- New mission "FND_Dealer"
  + Spawns in towns that don't have outposts near
  + Spawns a little shop template (objects)
  + Has a buy menu (see screenshots)
  + Leaves after some time
- New `A3A_fnc_commsMP` type "localChat"
  + Uses `customChat` and a 'temporary' radio channel to send the message
  + Players in the close vicinity only see the chat

### Please specify which Issue this PR Resolves.
N/A

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the Mission in Singleplayer?
2. [ ] Have you loaded the Mission in a Dedicated Server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

********************************************************
Notes:
- I only tested this in a local MP environment (`EDEN editor -> play -> MP`)
- There are still some TODO's that __might__ need to be fixed before release

#### TODO's
**Needs to be fixed**
- [ ] We need to redesign the missions menu to fit a button for this mission..
- [ ] Should killing dealer result in prestige punish? [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_FND_Dealer.sqf#L65)
- [ ] Name isn't set in-game [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_FND_Dealer.sqf#L76)
- [ ] Should we also deny opfor/blufor? [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_FND_Dealer.sqf#L104)
- [ ] balance the delete time [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_FND_Dealer.sqf#L148)
- [ ] Show some sort of notification that the dealer has left? [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_FND_Dealer.sqf#L164)
- [ ] These should actually be categorized in "mines" or "charges" [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_buyGear.sqf#L44-L45)
  + If that is hard, you should edit the UI to reflect these categories
- [ ] LOCALIZE [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_buyGear.sqf#L40)
- [ ] LOCALIZE [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_buyGear.sqf#L34)
- [ ] LOCALIZE [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_buyGear.sqf#L116)
- [ ] LOCALIZE [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_buyGear.sqf#L128)
- [ ] LOCALIZE [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_buyGear.sqf#L137)
- [ ] LOCALIZE [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_buyGear.sqf#L138)
- [ ] LOCALIZE [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_FND_Dealer.sqf#L105)
- [ ] LOCALIZE [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_FND_Dealer.sqf#L108)
- [ ] Localize [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/dialogs.hpp#L2872)
- [ ] Localize [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/dialogs.hpp#L3018)
- [ ] Localize [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/dialogs.hpp#L3135)

**Could be done later**
- [ ] The object placement could use some work [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_FND_Dealer.sqf#L16)
- [ ] (optional) Enemy QRF spawn near [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_FND_Dealer.sqf#L90)
- [ ] What is this for? (give it a good name) [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_FND_Dealer.sqf#L117)
- [ ] What is this for? (give it a good name) [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_FND_Dealer.sqf#L147)
- [ ] Find a more stable solution for this [link](https://github.com/JohnnyDeeee/A3-Antistasi/blob/7d80178baef35145b22964862a90f8863dbf0072/A3-Antistasi/functions/Missions/fn_buyGear.sqf#L37)

### CODE REVIEW

**Comment by JohnnyDeeee** [comment]
__Task__
afbeelding

__Task completed__
afbeelding

__Buy menu__
afbeelding

__Buy menu -> Some/Many weapons__
afbeelding

**Comment by Bob-Murphy** [comment]
Hi Johnny,
first of all thank you for the PR.
We ourselves have/had the plan to add some missions from version 1.8/1.9 to the current version. We also have this version as a repo of you want to check.
As we have other projects right now and we already changed some mission stuff it might take some time until you get proper feedback and/or we merge your PR.
But thank you!

**Comment by JohnnyDeeee** [comment]
@Bob-Murphy no worries, before i joined the Discord i was planning on making this only for my own fork, so no time wasted on my end ;)

**Comment by Bob-Murphy** [comment]
Closed due to inactivity as well as the mission-framework-rework coming up.

**Pull request closed without merging**
