### PR TITLE
Patch for bugs  in unstable found during Testing Tuesday 29.jun

### LINKED ISSUE #1986: Error in Choose Support
This popped up during my Testing,

20:44:31 Error in expression <};
};
};

private _friendlyUnits = if (_side == Invaders) then { units Invaders>
20:44:31   Error position: <_side == Invaders) then { units Invaders>
20:44:31   Error Undefined variable in expression: _side
20:44:31 File C:\Users\Florian\Documents\Arma 3 - Other Profiles\Lazejun\mpmissions\Antistasi-Altis.Altis\functions\AI\fn_chooseSupport.sqf..., line 199

---------> From the looks there is a mistake mentioning the side

### PR DESCRIPTION
**Pull request by HakonRydland**
Fixed `hasAce` missing the new prefix in new garage

## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information: Current bugs fixed:
- Wrong variable used in chooseSuport breaking support selection #1986 
- missing A3A_ prefix for hasAce var in new garage, breaking source detection and ace cargo info entry
- Added 2 Trucks to CoveredVehicles blacklist to prevent loading static weapons into them.

### Please specify which Issue this PR Resolves.
closes #1986 

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes: Should not be merged before end of Testing Tuesday, and a chance to fix remaining bugs found before it is over.

### CODE REVIEW

**Comment by HakonRydland** [comment]
Note per issue #1988 i disabled ambient audio on garage load, re-enabling them on unload.
additionally per same issue i added 3 more cba settings that allows for the disabling of the rearm, refuel, and repair features of the garage. (ie always state restoration)

**Comment by HakonRydland** [comment]
Per issue #1988 i have added:
- tooltip saying who is looking at a vehicle and who has locked a vehicle.
- vehicle customisation preservation

**Review by jaj22 — APPROVED** [review]
chooseSupport fix is correct. I wouldn't really know about the garage changes, not having read through the garage code in detail, but the individual changes look reasonable. I'm fine with spamming them in given that it's a new system.

**Comment by HakonRydland** [comment]
> chooseSupport fix is correct. I wouldn't really know about the garage changes, not having read through the garage code in detail, but the individual changes look reasonable. I'm fine with spamming them in given that it's a new system.

The support change was the primary reason for the review request, as @CalebSerafin has reviewed the garage before im relying on him for the garage changes

**Pull request merged**
