### PR TITLE
made the action to load/unload cargo a hold action

### PR DESCRIPTION
**Pull request by AylaMeo**
## What type of PR is this.
1. [ ] Bug
2. [x] Enhancement

### What have you changed and why?
Information: I made the action for loading cargo into vehicles a hold action, I originally made these changes for something else, but since they'd work here I figured they might be useful. 

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the Mission in Singleplayer?
2. [x] Have you loaded the Mission in a Dedicated Server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

********************************************************
Notes: I didn't travel travel very far with the cargo in testing, but I did test loading/unloading, nothing else should have been effected. Also I do have code for affecting vehicle mass with this logistics too. I didn't want to put both changes in one PR though.

### CODE REVIEW

**Comment by SonorousMeerkat** [comment]
Does it load as you hold, or do you have to hold it for x long, then the animation starts?

**Comment by Alsekwolf** [comment]
After, sorry probably should have clarified that. Basically my intention was to make it less cheesable to insta load cargo.

**Comment by SonorousMeerkat** [comment]
I see, I think a better solution would be to render the vehicle immovable while loading. There is already a, sometimes significant, loading time with the animation.

**Comment by Alsekwolf** [comment]
Well to be clear, I was just offering this as all the code was written.

**Comment by SonorousMeerkat** [comment]
That's fair, and thanks for doing so.
Similarly, I was using this as an opportunity to bounce an alternative option around.

**Comment by Bob-Murphy** [comment]
Tested it. Here's how it looks.
https://youtu.be/fC4zn7jYdVo

**Comment by Alsekwolf** [comment]
Oh side note, just in case it's not clear, the length it takes for the hold action is on line 82, `{}, [_object, player], 7, nil, false, false] call BIS_fnc_holdActionAdd;` You'd just change the 7 to whatever amount of seconds.

**Comment by Bob-Murphy** [comment]
Thank you very much for the code.
We know that the code still has a lot of things that can be improved and the loading/unloading is also one of the things.
We will definitively have a closer look at it and most likely adapt it to some point and combine it with other changes regarding the system at the same time.
I have it already added it to my to-do-list and will make sure that it won't be lost.
Also, don't worry if it needs some time for us to tackle this problem as we are currently working on a few other rather large things but again, thank you very much!
Every input is appreciated!

**Comment by Bob-Murphy** [comment]
Closed for now but will stay in my project to easily find the code if needed in the future.

**Pull request closed without merging**
