### PR TITLE
Convoy mission rework

### LINKED ISSUE #1492: Convoy parameters make them too difficult to intercept
**Is your feature request related to a problem? Please describe.**
Convoys targets are likely to be chosen very far from the HQ (anything within 2 * mission distance is valid), travel short distances (closest outpost/airport beyond spawn distance) and have little or no delay, which makes them difficult to reach with an effective force even if you drop everything.

If players do attempt to intercept the convoy, it's likely to be a massive performance hit because they'll be spawning garrisons way outside the operation zone.

**Describe the solution you'd like**
1. Reduce the target search radius.
2. Select random source bases rather than the closest, so that at least some convoys take a route with interception possibilities.
3. Increase the delay before the convoy starts driving.

Point 3 will require rearranging the code so that the convoy spawns immediately but doesn't start driving until the start timer is hit, otherwise convoys will spawn in vision if players head to the source early.

### LINKED ISSUE #1568: Convoy Mission, Armor Convoy should be stealable.
**Is your feature request related to a problem? Please describe.**
Armor Convoys lock the Armored Vehicle to prevent you from Stealing it.
https://github.com/official-antistasi-community/A3-Antistasi/blob/518facea4de9cdb090e0d5191445df3336402b4b/A3-Antistasi/functions/Missions/fn_convoy.sqf#L228

But the Text itself hints it's Steal OR Destroy so it should be able to be stolen.
https://github.com/official-antistasi-community/A3-Antistasi/blob/518facea4de9cdb090e0d5191445df3336402b4b/A3-Antistasi/functions/Missions/fn_convoy.sqf#L75

**Describe the solution you'd like**
We should remove the locking of the Vehicle cause the Text is missleading and disapointing.

**Describe alternatives you've considered**
We could also just remove the Part that mentions Stealing.

### LINKED ISSUE #1745: Error during 2.4 pre-test with A3A_fnc_convoy
```
arma3server_x64_2021-02-25_18-34-54 - Test 1 - Server

2021/02/26,  0:21:52 Bad conversion: string
2021/02/26,  0:21:52 Server: Object 2:28788 not found (message Type_124)
2021/02/26,  0:21:53 Error in expression < call A3A_fnc_NATOinit;_x assignAsCargo _veh;_x moveInCargo _veh;} forEach units>
2021/02/26,  0:21:53   Error position: <_veh;_x moveInCargo _veh;} forEach units>
2021/02/26,  0:21:53   Error Undefined variable in expression: _veh
2021/02/26,  0:21:53 File functions\Missions\fn_convoy.sqf [A3A_fnc_convoy]..., line 252
```

### PR DESCRIPTION
**Pull request by jaj22**
## What type of PR is this.
1. [X] Bug
2. [X] Change
3. [ ] Enhancement

### What have you changed and why?
General rebalance and fixup to make convoy missions more plausible to complete:
- Target selection uses much closer targets so you don't have to drive 8km to reach the convoy.
- Source selection prefers medium distances to allow more intercept options.
- Convoy units spawn immediately but have a 5-20 minute travel delay.
- Convoy travel script for vehicles so that they actually follow each other in convoy.
- Convoy vehicle spawning now much more reliable.
- allowCrewInImmobile used on armoured vehicles for consistency.
- Ammo convoys now actually contain loot-crate equipment.
- Fixed typo in reinforcement convoys.
- Escort vehicles RTB at completion.
- groupDespawner now removes spawner flag.

The spawning code includes a lot of generalised pathfinding support code:
- Find suitable navpoint for marker.
- Road connecting point/intercept.
- Road-to-road A-star.
- Find spawn positions along route.

This ended up with a lot more code and complexity than the original intention, as all reasonably simple spawning mechanisms had massive flaws. On the plus side, most of the pathfinding stuff should be generally useful, at least as examples.

Remaining issues:
- Disabled the convoy icons (inmuneconvoy) as the function does some potentially-problematic stuff that isn't icon-specific. Might add it back in shortly.
- The nearest navgrid point to a marker or spawnpoint can be quite far from the marker (common with factories and resources placed on a straight road), or in the case of spawnpoints, deep in a nest of roads that we'd rather not touch (see the middle airport on Altis). The first one could be fixed fairly cheaply on load, but I'm not sure how to handle the second.
- Arma AIs drive extremely poorly in many situations. Having the vehicles point in the right direction and avoid overtaking helps a lot, but other cases are still bad. Navgrid tweaks may help a bit, but not much.
- Convoys are probably too strong in terms of enemy firepower versus rewards. Depends how many vehicles get stuck.

### Please specify which Issue this PR Resolves.
closes #1745
closes #1568
closes #1492

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [X] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
You can request convoy missions from Petros to check the source/target selection results. 

Force-creating specific convoys. Run as server:
`[destMarker, sourceMarker, convoyType] spawn A3A_fnc_convoy;`
Convoy type can be left nil or empty string to autoselect, or choose a type from early in the function.

### CODE REVIEW

**Comment by jaj22** [comment]
missionRequest changes got lost in merging so I need to rewrite those.

**Review by Lazejun — APPROVED** [review]
Mostly checking how well its working,
Testing on Altis, BAF Modset, Requesting Missions from Default HQ Position.
1. Convoy: Money Convoy outpost_14 to factory_11, Vehicles spawned safe, departure time was 15 minutes 👍 
2. Convoy: Money Convoy outpost_22 to factory_11, one Bad spawn, one Vehicle spawned on the Bridge and apparently clipped into it and therefore exploded.
3. Convoy: Armored Convoy outpost_22 to outpost_42. same Bad spawn clipping into the Bridge and dying.
4. Convoy: Armored Convoy outpost_26 to outpost_22, safe spawns, only possible problem is the Helipad at that Outpost as its next to the Road, possible bad spawns when the Outpost spawns in, but should be fine as is, right now.
5. Convoy: Money Convoy outpost_22 to factory_2, same bad spawn, the first vehicle clipping into the Bridge.
6. Convoy: Money Convoy: outpost_7 to resource_5, Safe spawns, 15 minutes time to leave.
7. Convoy: Requested with Commands: Ammo Convoy outpost_39 to outpost_3, Safe spawns, Ammotruck has Items like the Outpost boxes, 15 minutes time to leave.
8. 
**Screenshots of the Bridge:** 
It seems 100% reproduceable, it's only the front Vehicle lost so could be fine i guess




Not sure how much we can do about the Bridge 🤷 

-------> In Conclusion:
Ammo Convoys get their Inventory 👍 
Armor Convoy Vehicle is not locked 👍 
15 minutes departure time almost all the time 👍 
Mission Request gives Targets that are pretty close to HQ, so should be reachable in time 👍 
Start and Endpoint of Convoys seems pretty good too 👍 
Almost all Vehicles spawned safe exept outpost_22 due to the Bridge 👍

**Comment by jaj22** [comment]
Fixed bridge spawning, at least in cases where the navpoints are in the right place. outpost_22 is fine but the current Altis navgrid isn't too careful about bridges, so others may break atm. There is also a simple hack to work around the bug where Arma fails to path in some positions and terminates the waypoint.

btw, I added a fourth parameter to force the convoy start time for debugging, so you don't have to wait 15 mins.

**Comment by Lazejun** [comment]
Played around with it again, and actually took a look at the Convoys driving now,
They seem to keep up with each other pretty well, Speed is ok and distance between Vehicles is pretty good.

Outpost_22s Bridge seems fine and safe to spawn for Convoys now.

But i ran into Issues with outpost_26 now:
For example 
```sqf
["outpost_33", "outpost_26", convoyType, 1] spawn A3A_fnc_convoy;
```
The Vehicles will spawn facing towards outpost_33 instead of the Road, ending with Vehicles spawning inside the floor as its Uphill and Vehicles spawning inside the Buildings within the Outpost.

Same will Happen if you take factory_11, but that won't happen by Mission request as its too close, but could be worth to look into.

Something similar to reproduce seems to be:
```sqf
["outpost_15", "outpost_41", convoyType, 1] spawn A3A_fnc_convoy;
```
They do spawn facing Outpost_15 but in my Test they just turned around and followed the Road, could be problematic in other Cases.

It seems like it does that on Targets that are close enough and if the Road is a Dead End.

**Comment by jaj22** [comment]
findPath is failing on outpost_26 to outpost_33 for some reason. Gonna need a few days to read that and figure out what its problem is.

RPT output:
```
 2:36:43 2021-06-01 01:36:43:563 | Antistasi | Debug | File: A3A_fnc_findPath | Starting pathfinding from [4544.08,15407.9,0] to [5587.3,15003.2,0] | Called By: A3A_fnc_convoy
 2:36:43 2021-06-01 01:36:43:576 | Antistasi | Info | File: A3A_fnc_findPath | Start [[4544.08,15407.9,0],0,false,[[5149,0,133]],0] at [4544.08,15407.9,0] End [[5587.3,15003.2,0],0,false,[[4535,0,338.6],[4481,0,178.475]],0] at [5587.3,15003.2,0] | Called By: A3A_fnc_convoy
 2:36:43 2021-06-01 01:36:43:608 | Antistasi | Error | File: A3A_fnc_findPath | Could not find a way search took 0.0419998 seconds max distance reached | Called By: A3A_fnc_convoy
```

Guessing that it has some rule like max path distance = 2 x direct distance, which falls over with outpost_26. outpost_15 to outpost_41 would have a similar problem.

**Comment by jaj22** [comment]
So findPath has a maximum path distance of 5x direct distance, but tracks count for 2x distance so it gives up on the longer Altis paths. I'm not sure if it needs a maximum path distance at all, as the pathing validity is pre-checked, but I just increased the maximum to 10x for the moment.

Works for outpost_33 -> outpost_26, outpost_15 -> outpost_41 and outpost_12 -> outpost_27 at least. outpost_26 -> factory_11 also works, which isn't a potential convoy (min 1km direct), but will be tripping up other functions.

**Review by Lazejun — APPROVED** [review]
should be good now 👍

**Pull request merged**
