### PR TITLE
UNA Faction Template (Aegis/Atlas Development Branch Dependency)

### PR DESCRIPTION
**Pull request by mongchat**
## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [X] Enhancement

### What have you changed and why?
Information: Just the template file for a full UNA faction, using Aegis and Atlas Development branches. Haven't been able to test it in game because I don't know how to but I didn't change anything other than classnames so it should work fine. They contract ION as SF.

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: Making sure it works fine and that Aegis/Atlas Dev branches are a required dependency - didn't know how to do this myself.

********************************************************
Notes:
[WS_AI_UNA_Arid.txt](https://github.com/official-antistasi-community/A3-Antistasi/files/10369147/WS_AI_UNA_Arid.txt)

### CODE REVIEW

**Review by Bob-Murphy — CHANGES_REQUESTED** [review]
This PR is build on top of Antistasi PLUS - not our version.
Please apply your changes to a fork of our unstable branch and create a new PR.
Thank you.

**Comment by Bob-Murphy** [comment]
See my review above.

**Comment by mongchat** [comment]
I was actually trying to make this a PR for Antistasi Plus, but I've never used the PR system before and have somehow got this in the wrong place. Apologies.

**Comment by Bob-Murphy** [comment]
Happens.
Make sure you select the correct branches when you open a PR. As the versions are connected to one another (Plus is a fork of our version), you can mess up quite a bit there.
If not completely sure, ask beforehand to prevent errors.

**Pull request closed without merging**
