### PR TITLE
RHS CHDKZ - Officer loadout & 3CB uniform support

### PR DESCRIPTION
**Pull request by ante185**
## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
Adds a case that gives the CHDKZ more uniform options when 3CB is loaded.
  New as of 23/12: 3CB Uniforms are now set according to climate.
Adds an officer loadout to the CHDKZ to more set them apart as a special.

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

### CODE REVIEW

**Review by Bob-Murphy — APPROVED** [review]
Not loaded but looks good.
@ante185  did you test it and check the RPT for any errors regarding the changes?

**Comment by ante185** [comment]
Converted to draft pending opportunity to test new changes

**Comment by ante185** [comment]
Temperate/Default, Arctic, Tropical, and Arid climates tested, no RPT errors, officer AS mission tested.

**Review by Bob-Murphy — APPROVED** [review]
lgtm

**Review by Bob-Murphy — APPROVED** [review]
lgtm

**Pull request merged**
