### PR TITLE
Added verb log level for those that need it

### PR DESCRIPTION
**Pull request by Toakan**
## What type of PR is this.
1. [ ] Bug
2. [X] Enhancement

### What have you changed and why?
Information:
Added a verbose level to the Log function. This is for our testing purposes to get every detail out that they can.

### Please specify which Issue this PR Resolves.
None

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the Mission in Singleplayer?
2. [X] Have you loaded the Mission in a Dedicated Server?

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

********************************************************
Notes:

I'll be making a follow up PR for the following functions so they will use this level from now on and clear up the debug spam.

- fn_equipRebel
- fn_NATOCrate
- fn_CSATCrate

@wurzel0701 (You requested this stuff, please make sure your projects make use of it 👍 )

### CODE REVIEW

**Comment by Bob-Murphy** [comment]
@Toakan Do we also want the ability to turn it on in the parameters?

**Comment by Toakan** [comment]
@Bob-Murphy Turn what on?

**Comment by Bob-Murphy** [comment]
Should log level 4 be added in the params.hpp or how do we activate it?
` class LogLevel
	 {
		  title = "Logging Level (Amount of detail in .rpt file)";
		  values[] = {1,2,3};
		  texts[] = {"Error", "Info", "Debug"};
		  default = 3;
	 };`

**Comment by Toakan** [comment]
The default should be 2, 4 is purely for our usage in testing situations and I'd rather it didn't get added to the front line where possible because it could increase CPU usage on populated servers if somebody were to leave it running for some reason.

**Pull request merged**
