### PR TITLE
Updated CSAT locations for new maps

### LINKED ISSUE #594: Set CSAT outposts and airfields in fn_initGarrison.sqf
Line 96 & following are for setting sides of positions so CSAT also has starting shit

```
private _mrkNATO = [];
private _mrkCSAT = [];
private _controlsNATO = [];
private _controlsCSAT = [];

if (debug) then
{
	diag_log format ["%1: [Antistasi] | DEBUG | initGarrisons.sqf | Setting Control Marks for Worldname: %2  .", servertime, worldName];
};

if (gameMode == 1) then
{
	_controlsNATO = controlsX;
	switch (toLower worldName) do {
		case "tanoa": {
			_mrkCSAT = ["airport_1", "seaport_5", "outpost_10", "control_20"];
			_controlsNATO = _controlsNATO - ["control_20"];
			_controlsCSAT = ["control_20"];
		};
		case "altis": {
			_mrkCSAT = ["airport_2", "seaport_4", "outpost_5", "control_52", "control_33"];
			_controlsNATO = _controlsNATO - ["control_52", "control_33"];
			_controlsCSAT = ["control_52", "control_33"];
		};
		case "chernarus_summer": {
			_mrkCSAT = ["outpost_21"];
		};
	};
	_mrkNATO = markersX - _mrkCSAT - ["Synd_HQ"];

	if (debug) then {
		diag_log format ["%1: [Antistasi] | DEBUG | initGarrisons.sqf | _mrkCSAT: %2.", servertime, _mrkCSAT];
		diag_log format ["%1: [Antistasi] | DEBUG | initGarrisons.sqf | _mrkNATO: %2.", servertime, _mrkNATO];
	};
}
else
{
	if (gameMode == 4) then
	{
		_mrkCSAT = markersX - ["Synd_HQ"];
		_controlsCSAT = controlsX;
	}
	else
	{
		_mrkNATO = markersX - ["Synd_HQ"];
		_controlsNATO = controlsX;
	};
};
```

### PR DESCRIPTION
**Pull request by Bob-Murphy**
## What type of PR is this.
1. [ ] Bug
2. [x] Enhancement

### What have you changed and why?
Information:
 Added map markers which should be CSAT at the start of the mission.   

### Please specify which Issue this PR Resolves.
closes #594 

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the Mission in Singleplayer?
2. [ ] Have you loaded the Mission in a Dedicated Server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

********************************************************
Notes:

### CODE REVIEW

**Comment by jaj22** [comment]
Don't those map names need to be lower-cased? toLower is used in the switch statement, and [the unreliable docs](https://community.bistudio.com/wiki/switch) claim that the comparison is case sensitive.

Also the _controlsNATO lines should ideally be pulled out into a single `_controlsNATO = controlsX - _controlsCSAT` array subtraction, like the markers are, but the code looks correct.

**Comment by Spoffy** [comment]
Good spot Pot, they absolutely do need to be lowercased

**Comment by PoweredByPot** [comment]
Thank you for credit I didn't deserve!

**Comment by Spoffy** [comment]
Hahaha, totally misread the name there! Thank you Jaj then ;) But sure, have a thank you too Pot for the sake of it :P

**Comment by wurzel0701** [comment]
The marker code is case-insensitive, as long as you write it correctly, it will pass.
outpost_1
OutpoST_1
OuTPoSt_1
will all get read in as an outpost

**Comment by wurzel0701** [comment]
Wow, i totally misread that, the world names in the cases have to lower case. Maybe not for the code but for the logic. And I would prefer _controlNATO = _controlNATO - _controlCSAT too

**Comment by CalebSerafin** [comment]
Changed to further testing as no tests are marked on the form.

**Comment by Bob-Murphy** [comment]
@Spoffy Don't I need to implement a `nato = nato - csat` line for every "type" that is changed within a map?

**Comment by wurzel0701** [comment]
Refactored the section a bit to reduce code redundancy. @Bob-Murphy you should keep the system which it uses now, in which you only have to state markerCSAT and controlsCSAT and the logic will do the rest

**Comment by Bob-Murphy** [comment]
@Spoffy Please make sure that this is still up-to-date and then merge.
Tell me when testing is needed.

**Pull request merged**
