### PR TITLE
Remove Jackals and Coyotes from BAF templates

### LINKED ISSUE #1362: 3CB Jackal camera issue.
**Describe the bug**
If you dismount from the commanders seat with a certain option, your camera bugs out.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
use "dismount right" from the commander's position

**Expected behaviour**
Dismount normally

**Screenshots**
N/A
**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): Any

[ ] LAN Hosted
[ ] Private dedicated server
[ ] Private dedicated server with Headless client(s)
[x] Community Server 1
[ ] Community Server 2
[ ] Community Test Server
[ ] Community Test Server 2

Modset: 3CB
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

### PR DESCRIPTION
**Pull request by SonorousMeerkat**
## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    Removed Jackals and Coyotes from BAF templates due to a camera bug.

### Please specify which Issue this PR Resolves.
closes #1362 

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in singleplayer?
2. [ ] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

### CODE REVIEW

**Comment by Lazejun** [comment]
What about the Coyotes tho
UK3CB_BAF_Coyote_Logistics_L111A1_D_DDPM","UK3CB_BAF_Coyote_Passenger_L111A1_D_DDPM"

Completly the same vehicle with the same Dismount options

**Comment by SonorousMeerkat** [comment]
Can you confirm that the bug exists with these? Not seen any reports about them.

**Comment by Lazejun** [comment]
You cannot reproduce this alone ...

**Comment by SonorousMeerkat** [comment]
Got someone on Main to look into it. Just wanted to know if you knew of a report about this one...

**Comment by Lazejun** [comment]
Tested with Chub, cannot happen on Host, happens on Other Players in the same way on Coyotes.

**Pull request merged**
