### PR TITLE
Add Antistasi Dev Deploy to Tools Folder

### PR DESCRIPTION
**Pull request by CalebSerafin**
Antistasi Dev Deploy is done and easy to use. It has been well tested. The program runs in a hidden window, perfect if you have something similar to VSCode's `save-and-run extension`. You can specify custom output folders and auto-open the output folder by using Antistasi Dev Deploy Configurator to change settings. 
Example Output: `"Antistasi-2-2.Kunduz"`. 
poweredbypot has tested it and the results come out satisfactory even on a complex workflow.

For more information on the benefits `Antistasi Dev Deploy` and where to get the `Antistasi Dev Deploy Configurator` App, visit [Antistasi-Dev-Deploy](https://github.com/CalebSerafin/Arma-3-Dev-Deploy).

The .gitignore was edited to include this executable.

### CODE REVIEW

**Comment by Bob-Murphy** [comment]
I don't know how I can set my review status to Approved but I approve that.
Tested it and it's nice!
Easy to use, you can choose your folder and stuff.
Bob likes that!

@Spoffy  from my side there is nothing speaking against the implementation into tools.

**Comment by Bob-Murphy** [comment]
Found it

**Comment by CalebSerafin** [comment]
@Spoffy Any problems with the PR?

**Comment by Spoffy** [comment]
Not at all, sorry for the delay @CalebSerafin! Didn't realise this had been sat around so long.

**Pull request merged**
