### PR TITLE
Fixed two errors with helicopter selling

### LINKED ISSUE #588: 2.2. Hellcat money farm
*Version:* 2.2.

*Mods:* none

*Environment*:  MP dedi.

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:***
Stolen Hellcats sell for 3900 - endless money farm:

We started a testrun with the current 2.2. files (4 players) and attacked an outpost. We got a massive spam of Mohawks and Hellcats. So we could hijack a nice amount of hellcats and could sell them for wooping 3900 each.
Because we can continue to do so it feels very out of balance.

Expected: Looted vehicle prices are more balanced and not so high that they break the economy part.

### PR DESCRIPTION
**Pull request by wurzel0701**
## What type of PR is this.
1. [X] Bug
2. [X] Enhancement

### What have you changed and why?
Information:
Reduced transport helicopter price down to 500
Transport helicopters are now correctly classified as such (no longer planes)
vehPlanes now contains only planes
Fixed wings are now all selling for 4000

### Please specify which Issue this PR Resolves.
closes #588 

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the Mission in Singleplayer?
2. [ ] Have you loaded the Mission in a Dedicated Server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

********************************************************
Notes: Not tested as laptop, minor changes which should not break anything. However, a startup would not do any harm

### CODE REVIEW

**Comment by Spoffy** [comment]
I've looked at removing the other air units from vehPlanes - I'm pretty sure we treat vehPlanes as containing all air units at other points in the code (but not 100% sure).

Can you check that?

**Comment by jaj22** [comment]
AIVEHinit does treat vehPlanes as containing all aircraft, so helicopters will not be initialized correctly if this is changed. Also I'm pretty sure transport planes were supposed to be included. The other uses are more questionable:

1. Non-airfield garages won't show helicopters due to their inclusion in vehPlanes. I thought this was a bug. Other people think it's intentional.

2. The asset save code is broken (harmlessly) due to double-counting attack helicopters. It will break badly if you remove much from vehPlanes, as it's supposed to save anything that has a value in the timer object, including transport helicopters and transport planes.

`_veh isKindOf "Plane"` is perfectly adequate if you want to check whether something is a plane, so I'd rename vehPlanes to vehAir or vehAircraft and keep it as a catch-all.

**Comment by Spoffy** [comment]
I'd agree with Jaj here, I'd use either `vehFixedWing` or `isKindOf "Plane"`. The latter is going to be far more robust here, so I'd use that.

Regarding helicopters - I think we decided all transport helicopters should be removable from non-airbase garages, and others require an airbase. But it's an entirely separate issue, so I won't talk about it further :)

**Comment by wurzel0701** [comment]
Ok, I will revert all this and just fix the line in sellVehicle, closing this PR

**Pull request closed without merging**
