### PR TITLE
Map Port of Pulau

### PR DESCRIPTION
**Pull request by ante185**
## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:

Initial draft of the terrain [Pulau](https://steamcommunity.com/sharedfiles/filedetails/?id=1423583812&searchtext=pulau)

Features: 
two main islands
two airbases divided between the two
21 towns and villages
16 outposts
11 resources
2 seaports
2 factories

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

Picture and whiteboard needs updating
stringtable needs to be looked at

********************************************************
Notes:
would probably see an substantial gameplay improvement with the reintroduction of sea assaults.

### CODE REVIEW

**Comment by jaj22** [comment]
Checked out the left hand island a bit. Notes:

1. outpost_8 has a couple of undersized vehicle markers. The larger one has junk on it but in theory that should get cleared on init.
2. Airport seems a bit underdefended.
3. No specops markers on the island.

Gonna need to test some vehicle spawn -> road pathfinding too.

**Comment by ante185** [comment]
Updated

**Review by jaj22 — CHANGES_REQUESTED** [review]
outpost_4: Total infantry ingress failure. Need to cut out some of the hbars on both entrances I think.
outpost_5: Partial infantry ingress failure. North side works but could probably do with removing the wall near the path on the south side.
outpost_6: Infantry can't path through the archway for some reason. Not sure what you can do about that. They seem to figure out the long way around at least.
outpost_3: Infantry attempting ingress from the SW quarter tend to get stuck. Could probably remove a wall or two. Vehicle exits are pretty scary too, although they seem to work, at least without any additional obstructions.

**Comment by ante185** [comment]
>1.  outpost_4: Total infantry ingress failure. Need to cut out some of the hbars on both entrances I think. 
>2. outpost_5: Partial infantry ingress failure. North side works but could probably do with removing the wall near the path on the south side. 
>3. outpost_6: Infantry can't path through the archway for some reason. Not sure what you can do about that. They seem to figure out the long way around at least. 
>4. outpost_3: Infantry attempting ingress from the SW quarter tend to get stuck. Could probably remove a wall or two. Vehicle exits are pretty scary too, although they seem to work, at least without any additional obstructions.

1, 2, and 4 have been addressed. outpost_6 yeah there's not a lot we can do about that? The piece with the arch is massive, can't just hide the arch.

**Review by jaj22 — APPROVED** [review]
Fine by me now, although I expect Bob will want a look at it.

**Review by Bob-Murphy — APPROVED** [review]
Will be tested in on the test servers

**Pull request merged**
