### PR TITLE
3CB AAF desert / Brown AAF

### PR DESCRIPTION
**Pull request by ante185**
## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
3CB provides the AAF with a whole set of brown infantry equipment, this alternate template uses the brown digital infantry camo and replaces the vehicle set with tan vehicles. 
Making it more suitable for less green terrains.

Specific changse:
1. vehicles have been replaced with closest possible tan equivalent.
2. Infantry uniforms, vest, and helmets have been changed from green digital to brown digital.

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
4. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:
A lot of the aircraft did not have suitable tan/desert equivalents and the way i see it there's 3 options:
1. [ ] Use only tan or desert camouflaged air vehicles.
2. [x] Use original green digital air vehicles.
3. [ ] Mix, using green digital air vehicles where there are no suitable tan desert camouflaged variants.

Currently option # 2 is what is in this PR, but i can see reason for either of the three options

### CODE REVIEW

**Comment by ante185** [comment]
Request for opinions/feedback on the aircraft & helicopter lineup, see notes

**Comment by MeltedPixel** [comment]
> Reverted the brown helicopters to digital green helicopters.

Curious on why you went with the Green Digital instead of the brown. I see you requested feedback but looks like it got missed while we were on other projects.

IMO, as long as the choice wasn't because of limited selection of helicopters, I think it would make sense for them to get Tan/Brown air vehicles as well if their ground vehicles are also in that scheme.

Otherwise, looks fine barring you've done ample testing on the new classnames. No errors on my quick test.

**Comment by ante185** [comment]
> > Reverted the brown helicopters to digital green helicopters.
> 
> Curious on why you went with the Green Digital instead of the brown. I see you requested feedback but looks like it got missed while we were on other projects.
> 
> IMO, as long as the choice wasn't because of limited selection of helicopters, I think it would make sense for them to get Tan/Brown air vehicles as well if their ground vehicles are also in that scheme.
> 
> Otherwise, looks fine barring you've done ample testing on the new classnames. No errors on my quick test.

I mainly undid it because of the lack brown helicopters, though their airplanes are still brown/tan.
There is a *couple* ground vehicles that the og 3cb aaf has that this template doesn't have but i belive that to be much less significant, iirc of the ground vics it's only the vodniks that are missing, everything else could be replaced with US, KRG and ADA vehicles.
Classnames should be fine as they'd all be used in the other 3cb templates

**Comment by MeltedPixel** [comment]
> I mainly undid it because of the lack brown helicopters, though their airplanes are still brown/tan. There is a _couple_ ground vehicles that the og 3cb aaf has that this template doesn't have but i belive that to be much less significant, iirc of the ground vics it's only the vodniks that are missing, everything else could be replaced with US, KRG and ADA vehicles. Classnames should be fine as they'd all be used in the other 3cb templates

Hmm, I still lean into the brown scheme but I get it. Maybe brown/tan where applicable? Like a mix.

**Comment by ante185** [comment]
> Hmm, I still lean into the brown scheme but I get it. Maybe brown/tan where applicable? Like a mix.

Personally not a fan of mixing, I'd like to have one or the other but unfortunately i feel like too many too important helicopters are missing for it to work out.
Perhaps someone will come with a tie breaker on this?

**Comment by Bob-Murphy** [comment]
@ante185 at least some helos are using the green AAF pattern.
Wouldn't it be more fitting to either use `CSAT (Brown)` or `Desert` where applicable?
Neither of them have any flags or other decals.
ArmA 3 Screenshot 2023 10 19 - 14 41 47 36

**Comment by ante185** [comment]
> @ante185 at least some helos are using the green AAF pattern. Wouldn't it be more fitting to either use `CSAT (Brown)` or `Desert` where applicable? Neither of them have any flags or other decals. ArmA 3 Screenshot 2023 10 19 - 14 41 47 36

CSAT's brown HEX i gotta turn down, but there does appear to be a number of tan/desert camos available, however as best as i can tell there's no unique vehicle classes classes that use them, so that'd be another set of re-textured vehicles to put into config_fixes

**Comment by ante185** [comment]
Helicopter lineup updated, plane loadouts set

**Review by Bob-Murphy — APPROVED** [review]

**Pull request merged**
