### PR TITLE
Rebel grenades and vests

### PR DESCRIPTION
**Pull request by SonorousMeerkat**
Replaces: 
Most Rebel uniforms,
Initially available weapons to 2 primary's and 2 secondary's and 1 AT stick where suitable, (with their respective magazines)
Some of the Mines,
the initial grenades,
Initial backpacks,
In theory, the starter vests (untested due to PBP adding every vest with less than level 2 armor to the arsenal )
And finally the startLR radio available to 3CB.

### CODE REVIEW

**Comment by SonorousMeerkat** [comment]
I've tested all currently integrated selections for all currently integrated modsets.

**Comment by PoweredByPot** [comment]
I HAVE ALREADY MERGED THIS INTO MY WORK WITH MODIFICATIONS.
PLEASE DO NOT MERGE!!!!

**Comment by SonorousMeerkat** [comment]
What modifications? Just so i know what is happening with MY project.

**Comment by SonorousMeerkat** [comment]
Because i need *either* the changes/changed files OR this to be merged so that i can carry on with the project...

**Comment by SonorousMeerkat** [comment]
This has been corrected with a few key fixes and works with the current version of unstable. Therefore i would like to have Pots don't merge overruled. If he changed things in his branch that need changes here, he can make them himself post merge.

**Comment by Bob-Murphy** [comment]
Prioritisation for rebel starting gear in following order:
Shotgun, Bolt-action, smg

**Pull request merged**
