### PR TITLE
fixed white space issue with log processing

### PR DESCRIPTION
**Pull request by HakonRydland**
## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    fixed array processing for large log lines, should now display them with each element on a new line 

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

### CODE REVIEW

**Review by jaj22 — APPROVED** [review]
(resists temptation to bitch about own code)

@Bob-Murphy Still needs practical testing because I only ran a non-define version in the debug console.

**Comment by jaj22** [comment]
Wait wait, that's the version from before I fixed the conditional on the second `find`.

**Comment by Bob-Murphy** [comment]
I'll prepare some food, you have some more time to bitch at your own code.
@ me once you are sure :D

**Review by jaj22 — APPROVED** [review]
Ok, good to test now.

@Bob-Murphy

**Review by Bob-Murphy — APPROVED** [review]
Seems to work.
Here an output from the server:
```
2021/09/21, 10:14:01 2021-09-21 17:14:01:149 | Antistasi | Verbose | File: A3A_fnc_selectVehicleType | SelectVehicleType: Preselection done possible vehicles are ["rhsusf_m1245_m2crows_socom_d","rhsusf_M1078A1R_SOV_M2_D_fmtv_socom","rhsusf_m1025_d_m2","rhsusf_m1043_d_m2","rhsusf_m1045_d","rhsusf_m1151_m2crows_usarmy_d","rhsusf_m1151_m2_v1_usarmy_d","rhsusf_m1151_m2_lras3_v1_usarmy_d","rhsusf_m1151_m240_v1_usarmy_d","rhsusf_m1151_m2_v2_usarmy_d","rhsusf_m1151_m240_v2_usarmy_d","rhsusf_m966_d","rhsusf_M1220_M153_M2_usarmy_d","rhsusf_M1220_M2_usarmy_d","rhsusf_M1230_M2_usarmy_d","rhsusf_M1232_M2_usarmy_d","rhsusf_M1237_M2_usarmy_d","rhsusf_m1240a1_m2_usarmy_d","rhsusf_m1240a1_m240_usarmy_d","rhsusf_m1240a1_mk19_usarmy_d","rhsusf_m1240a1_m2_uik_usarmy_d","rhsusf_m1240a1_m240_uik_usarmy_d","rhsusf_m1240a1_mk19_uik_usarmy_d","rhsusf_m1240a1_m2crows_usarmy_d","rhsusf_M1239_socom_d","rhsusf_M1238A1_socom_d","rhsusf_m1025_d","rhsusf_m1043_d","rhsusf_m998_d_2dr_fulltop","rhsusf_m998_d_2dr_halftop",
2021/09/21, 10:14:01 >>> "rhsusf_m998_d_2dr","rhsusf_m998_d_4dr_fulltop","rhsusf_m998_d_4dr_halftop","rhsusf_m998_d_4dr","rhsusf_m1151_usarmy_d","rhsusf_m1165_usarmy_d","rhsusf_M1220_usarmy_d","rhsusf_M1232_usarmy_d","rhsusf_m1240a1_usarmy_d"] | Called By: A3A_fnc_createGarrisonLine
```

**Pull request merged**
