### PR TITLE
Added logging for unlocks

### PR DESCRIPTION
**Pull request by HakonRydland**
## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    all unlocks after server init is now logged
unlockItemLogging

### Please specify which Issue this PR Resolves.
Bob request no issue made for it

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in singleplayer?
2. [x] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
start a new campaign and unlock a few items, check the logs, then load a previous save and do the same. it should only log when you unlock stuff and not when initializing the arsenal
********************************************************
Notes:

### CODE REVIEW

**Comment by jaj22** [comment]
Seems a bit weird putting this in JNA rather than unlockEquipment.

**Comment by CalebSerafin** [comment]
Unlock equipment doesn't seem to be called as many places as arsenal_addItem (Cargo and LoadInventory). So that decision is probably fine as arsenal_addItem should be the endpoint anyway. It looks fine right now, but I'll give it a proper review tomorrow morning.

**Comment by jaj22** [comment]
Every other use of arsenal_addItem is internal to JNA, which never calls with -1 itself. I'm pretty sure that unlockEquipment is the sole entry point for unlocking in Antistasi.

Note that most addItem calls don't even execute on the server, but the debug output here assumes that they do. It actually works out, because unlockEquipment is always server-executed, and it's the only -1 call. Similarly the serverInitDone check does nothing, because the -1s are set on game load by directly writing jna_datalist rather than using addItem.

**Comment by HakonRydland** [comment]
your right @jaj22 i will move it to unlockEquipment, i will also make it remoteExec to the server

**Review by CalebSerafin — APPROVED** [review]
Okay, there is a bit of weirdness related to the arsenal and when it decides to say that something is unlocked. If a weapon exceeds unlock amount -> persistent save -> Logs weapon unlocked -> Exit reload -> add some of that weapon type from a crate/arsenal tick over -> JNA announcing the weapon has been unlocked -> Logs weapon unlocked again.

This can be manipulated to either say it once finally or drag out the process and have it repeat this many times.

However, this a quirk of the arsenal, and exposing this flaw may lead to better improvements of the arsenal/unlock system.

**Comment by jaj22** [comment]
I guess you do still need the serverInitDone because you don't want it spamming on initialRebelEquipment.

By convention I think we normally put the fn_functionname form in the logging filename (rather than A3A_fnc_functionname). It's five characters shorter and doesn't give any less information at least.

**Comment by Giddius** [comment]
currently all messages have the function as "fn_something" except for the punishment logging messages they actually have:
"fn_something.sqf", the general convetion seems to be 

"fn_functionName"

**Comment by HakonRydland** [comment]
> I guess you do still need the serverInitDone because you don't want it spamming on initialRebelEquipment.
> 
> By convention I think we normally put the fn_functionname form in the logging filename (rather than A3A_fnc_functionname). It's five characters shorter and doesn't give any less information at least.

while i can stick to convention i find it nicer to have it as function name, as it makes it faster to find the function whit a quick search, although it is admittedly just a tiny bit faster than fn_functionname, and not all files in antistasi has a filename variable for logging so i will change it.

**Review by CalebSerafin — APPROVED** [review]

**Pull request merged**
