### PR TITLE
Isla duala playtest adjustment

### PR DESCRIPTION
**Pull request by ante185**
## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
General cleanup and adjustments of assets
Moved or removed a number of control markers.
Testing a change to make the bridges indestructible on more than the host machine.
Moved the support corridors further away from land

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

### CODE REVIEW

**Comment by ante185** [comment]
Tested bridges by hosting the mission and letting @Tiny-DM join and try and destroy them. Reported the bridges as indestructible.

**Comment by jaj22** [comment]
What's the change to the bridges? The SQM diff is unreadable as usual.

**Comment by ante185** [comment]
> What's the change to the bridges? The SQM diff is unreadable as usual.

`					init="if (isServer) then {{_x allowDamage false; _x  enableSimulation false;} forEach nearestObjects [this, [""Land_ibr_mostd_bez_lamp"", ""Land_ibr_mostd_stred30""], 250];};";
->
					init="if (true) then {{_x allowDamage false; _x  enableSimulation false;} forEach nearestObjects [this, [""Land_ibr_mostd_bez_lamp"", ""Land_ibr_mostd_stred30""], 250];};";`
					
basically, made the if statement to always be true instea of is server.
Coulda shoulda removed the if statement but this was faster and i had to do it several times

**Comment by jaj22** [comment]
Weren't we putting these in the map's initServer to make them readable? Can use initPlayerLocal if you need it to run everywhere.

**Comment by ante185** [comment]
these were always in game logics placed by the bridges, it's just (appears as) having the isServer as the condition was wrong

**Comment by ante185** [comment]
Moved the support corridors further away from land, particularly the invader corridor was obnoxiously close to the mid-east airbase, making the enemies pop in in front of the players and be easy to spawn camp

**Comment by jaj22** [comment]
> these were always in game logics placed by the bridges, it's just (appears as) having the isServer as the condition was wrong

Yes, but in #3424 we moved similar code into actual code files. And I like that.

**Comment by ante185** [comment]
> Yes, but in #3424 we moved similar code into actual code files. And I like that.

It's just that I don't have any way of retesting this - this appears to work and isn't that big of a change from what's currently merged

**Review by jaj22 — APPROVED** [review]

**Comment by jaj22** [comment]
Tested the bridge code with local client + DS, works.

**Pull request merged**
