### PR TITLE
Are you interested in merging any of my changes to your main version?

### PR DESCRIPTION
**Pull request by TheShade66**
## What type of PR is this.
1. [ ] Bug
2. [X] Change
3. [X] Enhancement

### What have you changed and why?
Information:

- heavily expanded music script which plays music only SOME of the time (roughly 50 %) to prevent annoyance (uses music from A3, CUP, VN, GM // To do: (need to add dependecies selector)

- custom VN + GM faction, with working logistics nodes and everything else -> best assets in A3

- custom crates for vehicle spawning and arsenal (in missions.sqm, chernarus only ATM) - immersion

- expanded placeable buildings, allowing players to set up a camp

- modified all 2035 assets on the chernarus map to better authenticity (removed Large towers, replaced with Tower bunkers)

- disabled simulation or enabled dynamic simulation on preplaced assets in scenario to gain better performance

- slowed movement speed of all spawned patrols -> FIXED the "jerky" movement speed that could be observed before

- lowered the price of loot crate & rally point in order to make the mission easier for low player numbers (we play w/ 1-3 players)

    

### Please specify which Issue this PR Resolves.
closes #XXXX
none

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the mission in LAN host? 
Yes! works as intended, didn't change any actual functions apart from music script.
3. [X] Have you loaded the mission on a dedicated server?
Yes! works as intended, didn't change any actual functions apart from music script.

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

Add selector to music script, or simply remove the VN,GM,CUP music.

### How can the changes be tested?
Steps: 
play with GM, VN enabled. 

********************************************************
Notes:

I can provide individual changes in isolation, instead of you having to change the entire fileset.

### CODE REVIEW

**Comment by Bob-Murphy** [comment]
Hey Shade,
first of all thank you very much for the PR.

As you might not now, for the next release we will change from separate missions to a mod.
Your changes seem to be based on the old mission format, hence we will not be able to simply merge it but certainly would need to go through, cherry-pick and then adapt it.

Nevertheless, it's certainly good to have it in here so we can dive in it, check what you've done.
Cheers!

**Comment by TheShade66** [comment]
Thank you!

I was unaware of the coming change, best of luck with your efforts! This Scenario is in my opinion the best arma has to offer.

As a quick mention of the type of changes made:

- when calling UPSMon script, add limited to parameters. It will fix the "twitchy" movement speed of all patrols.


Let me know if you would like me to submit ideas or the actual file which reflects all of my changes.

Best!

**Comment by Bob-Murphy** [comment]
We have something in the works to replace UPSMON as it's outdated AF and produces more than just a few issues.
If you'd like to see what we have done since October, we will start a test later today on our test servers.
Feel free to hop on, play with the community and have a look.

If I saw it correctly you are on our discord.
You can subscribe to pings for development related topicsin the topic-subscription channel so you can keep up to date.

And cheers for the compliment. It's always nice to hear that people like what we do.

**Comment by Lazejun** [comment]
There is not a Single Commit done by You Shade, this is not even your Fork that you are trying to Merge.

You are trying to Merge Unstable from Antistasi Plus into this.

**Comment by TheShade66** [comment]
closing fork, it connected me from the Plus version to your repository.

My mistake!

**Pull request closed without merging**
