### PR TITLE
params update

### LINKED ISSUE #3057: Update default params
Some default params are potentially not giving the players the best experience.
Hence following default values for params should be changed:
A3A_GCThreshold from off to 4h --> GC improves performance maintains stability
A3A_selfReviveMethods from off to on --> artificially not giving players the option to use this new feature is hindering in my eyes
membershipEnabled from on to off --> most people playing don't use / have the need for the membership feature as they play in closed communities

### PR DESCRIPTION
**Pull request by Bob-Murphy**
## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Updates parameters as readable in #3057
### Please specify which Issue this PR Resolves.
closes #3057

### CODE REVIEW

**Comment by jaj22** [comment]
If we're changing default membership to off then the natural change is to disable FF punishment by default too.

**Comment by Bob-Murphy** [comment]
Does disabling FF only stops the punishment or also the logging and the pop-ups?

**Comment by Tiny-DM** [comment]
@Bob-Murphy Yes. fn_punishment_checkstatus and fn_punishment_FF_addEH exit if the option is disabled (where the pop-ups and logging are), and the latter is the entry point for all FF checks so it wont trigger no matter what

**Comment by Bob-Murphy** [comment]
Opened #3060 as an issue for separate change request regarding the FF stuff.

**Review by jaj22 — APPROVED** [review]

**Pull request merged**
