### PR TITLE
Large fuel tank saving

### LINKED ISSUE #2653: [Bug]: Large fuel tank (vanilla) does not save
...because saving these things apparently relies on the general HQ vehicle-saving routine, and that excludes Reammobox_F which the this fuel tank class inherits from for some reason.

 Not sure if already fixed in one of the buy menu PRs.

### PR DESCRIPTION
**Pull request by killerswin2**
## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    Adds and override system so that objects that need to be save, can be.

### Please specify which Issue this PR Resolves.
closes #2653

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

### CODE REVIEW

**Review by Lazejun — COMMENTED** [review]
Saving works etc. but this lacks saving Fuel amount so you could get Free 10000 Liters from save/load.

**Comment by killerswin2** [comment]
saving fuel should now work. Forgot to call the state function.

**Review by Lazejun — APPROVED** [review]

**Review by jaj22 — APPROVED** [review]
I'm amused that you were so desperate not to add another element to the worst remaining `if` in the codebase that you just duplicated all the code :P

Whatever. Needs a rethink at some point, probably setting a flag on objects that should or shouldn't be saved.

**Comment by killerswin2** [comment]
I thought about the code a func, and converting the logic to a switch statement, but I just wanted a quick fix.

**Review by Bob-Murphy — APPROVED** [review]
lgtm

**Pull request merged**
