### PR TITLE
Added missing parenthesis around sleep expression

### PR DESCRIPTION
**Pull request by Zarickan**
## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
`sleep` is a unary command which has a higher precedence than the binary + command, thus 
```sqf
sleep 1 + (random 1);
// parses as
(sleep 1) + (random 1);
```
Which is not a valid expression (as sleep returns nothing), what was probably intended is:
```sqf
sleep (1 + (random 1));
```
which can be written simpler like this:
```sqf
sleep (1 + random 1);
```

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

### CODE REVIEW

**Comment by Zarickan** [comment]
For `fn_AIreactOnKill.sqf` and `fn_artillery.sqf` the `sleep n` would likely have been evaluated before the binary `+` which probably meant that the sleep would always be for a constant amount of time. In both these scripts my fixes should result in longer sleeping times the before.

**Review by HakonRydland — DISMISSED** [review]

**Comment by Bob-Murphy** [comment]
@HakonRydland please review the additions

**Comment by HakonRydland** [comment]
The iinfo can have the SP/MP part stripped as we only support MP now.

**Review by HakonRydland — CHANGES_REQUESTED** [review]
alter the info to only log version and remove the define and it should be fine.

Note: in the future dont add out of scope alterations to a PR, especially after original changes was approved.

**Comment by Bob-Murphy** [comment]
dead

**Pull request closed without merging**
