### PR TITLE
Make Antistasi Again!

### PR DESCRIPTION
**Pull request by killerswin2**
## What type of PR is this.
1. [x] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    This PR finally fixes all issues, we have made the most perfect Arma 3 mission.
    God Bless Petros!

### Please specify which Issue this PR Resolves.
closes ALL ISSUES

### Please verify the following and ensure all checks are completed.
N/A good code

### Is further testing or are further changes required?
N/A good is completed

### How can the changes be tested?
Steps: 

********************************************************
Notes:
please help. this is tiny. I am locked in killers basement being forced to translate technical papers into antistasi features. first it was P = NP, now this...

### CODE REVIEW

**Comment by ante185** [comment]
lgtm

**Comment by Tiny-DM** [comment]
No code errors, nothing (bad) happens when ran. lgtm

**Comment by CalebSerafin** [comment]
boxes-check
Software Developers Looks Good to Me LGTM

**Comment by Callum511** [comment]
Get back in killers basement and fix another 100 bugs

**Review by targetingsnake — CHANGES_REQUESTED** [review]
Just no.

**Review by targetingsnake — APPROVED** [review]

**Pull request closed without merging**
