### PR TITLE
Added Vanilla_AI_NATO_Temperate

### PR DESCRIPTION
**Pull request by CalebSerafin**
## What type of PR is this.
* Bug
* Change
3. [x] Enhancement

### What have you changed and why?
* Added Vanilla_AI_NATO_Temperate

### Please specify which Issue this PR Resolves.
closes D13 on the speed sheet

### Please verify the following and ensure all checks are completed.

2. [ ] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
* Yes (Can't test, no implementation)

### How can the changes be tested?
Implement the implementation which Implements the new templates blockchain Kubernetes.

### CODE REVIEW

**Review by Lazejun — CHANGES_REQUESTED** [review]
Making Militia sort of a PMC is a cool interesting idea,

Your Crewman look weird in a Heli Pilot Coverall, Vanilla Arma Crewman use the Recon Fatigues.

Your Pilot is a Jet Pilot right now, that is fine but questionable since most Pilots players ever see are the Helipilots and it might be weird for people to see them wear all that Equip for a Tiny Helicopter.

I realy dislike the heavy use of Apex DLC and Marksman DLC, Nato Woodland is free content so it should be able to be used on all Maps without forcing players to use a DLC.
-----> Vehicles (Only the LSV), Gear all Spars, MArksman DLC DMRs, Apex DLC sights, Marksman DLC sights.

**Comment by CalebSerafin** [comment]
Paid items have been watered-down to at least a 2:1 Vanilla:Paid ratio (Some even removed completely from some categories). There are now plenty of items and vehicles for Base game people. If I missed a category, please let me know.

**Review by Lazejun — APPROVED** [review]
Seems alright now, you still have that annyoing merge conflict cause of the Hints i touched 👀

**Comment by CalebSerafin** [comment]
@Lazejun please merge.

**Pull request merged**
