### PR TITLE
Bug Fixes for city supplies 🛢️, QOL for fuel ⛽, and Out of Bounds Check for Moving assets. 

### LINKED ISSUE #2164: [Bug]: When Vehicle Load despawns it still blocks the seats
### Describe the bug

When you transport City Supplies in a vehicle and the mission timer runs out, the palette with the supplies despawn.
The vehicles cargo is still occupied, but you cannot unload anything since nothing is loaded, keeping the seats disabled.

Workaround: Garage -> Ungarage to reset vehicle

### How to reproduce

Spawn City Supply, Load in Offroad, Skip Time to Fail Mission.

### Version

latest on Community Servers as of 08.10.2021

### Have you altered the code?

No

### What i have changed

_No response_

### Map

Takistan

### What server?

Community Server 1, Community Server 2

### Time bug occured (Server time/UTC)

_No response_

### Mods

_No response_

### Additional context

Suggestion: When Driver enters/leaves the car, check if cargo is still there, else free cargo.

As a side note, the city supplies usually leave an empty pallets when the mission is completed (not sure if the mission fails it will stay as is, leave palette or despawns completely, maybe a solution is possible utilising the pallets somehow.

### LINKED ISSUE #2193: [Change Request]: Allow Far away HQ assets to be carried back.
### Is the requested change related to a problem?

When an HQ object becomes too far from HQ it cannot be moved.
This can easily happen due to objects being pushed by a vehicle or rolling down a hill.

The error message will not help anyone who does not know what a "relative zone center" is.

> "This asset needs to be closer to it relative zone center to be able to be moved."

### Describe the solution you'd like.

1. Delete the line responsible.
https://github.com/official-antistasi-community/A3-Antistasi/blob/700c3bddb6310cbb8ebc5c6795ad911c53cd2d5c/A3-Antistasi/functions/Dialogs/fn_moveHQObject.sqf#L19

2. Add a variable that checks if the object was out-of-bounds before picking it up (HQ boundary).
3. If the object was out of bounds, allow the player to carry it out of bounds for him to correct it's position.

### Alternative solutions

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by killerswin2**
## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    Added an attachedTo check on the pallet to see if it was attached to anything before deletion.
Changed color of the fuel marker and made the small fuel containers purchasable for non-commanders.
Added a check for moving objects out of bounds, allows for objects that are out of bounds to be moved.

### Please specify which Issue this PR Resolves.
closes #2193 
closes #2164 

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

### CODE REVIEW

**Review by CalebSerafin — CHANGES_REQUESTED** [review]
Is this meant to be reviewed yet?
image

**Comment by killerswin2** [comment]
@CalebSerafin you said you had new ideas on doing the out of bounds check?

**Comment by CalebSerafin** [comment]
I thought about it for a while and realised that it's impossible to all our current constraints. 

Constraints:
1. If box is outside of bounds then we don't want the player to carry it further out of bounds. 
2. The box must be carried back to Hq zone. 

Easy case:
Check that the boxer's delta position goes somewhere towards HQ zone. Knock the box out of hands if it it does not go to the HQ zone. This will allow the player to carry the box straight to HQ.

Stuck case:
The box falls down behind some objects.
In order to return the box, the player must walk a route that leads further away before it can come closer to HQ zone. This violates constraint 1.

Possible Solutions:
1. Scrap constraint 2 by auto positioning the box when it's outside of the HQ zone. A player can trigger this, or a periodic loop check.

2. Keep constraint 2 and add the auto position as an additional action if the player concludes that it is logically stuck.

**Comment by CalebSerafin** [comment]
Actually, there is a really neat solution to this. But it requires a mind shift.

Our current position validation is reactive to an error. This attaches the box to the player and allows to player to go as they please, and only checks the box's position after it has moved. This prevents reverting to the old spot as another object may have taken its place.

What we can migrate to is proactive position validation. The box will stay in its place throughout the "carry" process. The player will carry a "virtual" box. When the player wants to deploy the box, it will validate the position, if it does not like the position it will abort the deploy process and tell the player to retry or abort.

This could be applied to all objects that have some sort of position validation.

**Comment by Lazejun** [comment]
So this branch is basically fucked as the repo was deleted.

I tried parts of it but ran into other issues

Part 1 The Fuel marker Color and Everyone canbuy fuel thing, that's pretty simple has no changes requested.

Part 2 Unloading a random item from the Vehicle,
This does not work in its current state, unloading is to slow, it has to be instant, it needs sleep of 0.1 minimum so it's unloaded before deleting.

Also the issue that unloading will unload the LAST object not the one that will be deleted.

#2346 

Part 3 the Out of bounds check, it sounded like frost has a few better ideas to the solution so probably best if he takes that part.

**Comment by CalebSerafin** [comment]
Moving to an organisation branch.

**Pull request merged**
