### PR TITLE
Changing rifleman load coef.

### PR DESCRIPTION
**Pull request by killerswin2**
## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    Rifleman should have a normal loadcoef, as rifleman rarely ever hack a drone.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

### CODE REVIEW

**Comment by Bob-Murphy** [comment]
As you can see every unit has some traits increased and others decreased. This was done to differentiate from one another.
This chance would kinda break it as it would give the riflemen only positive changes.

TL - 0,8+0,8+1,4 = 3
Riflemen - 0,8+0,8+1 = 2,6 (was at 2,8 before your change so was already overall better than other units)
GL - 1,2+0,8+1 = 3
AR - 1,2+0,8+1 = 3
Engi - 1+1+1 = 3
Medic - 1+1+1 = 3

The extra abilities like medic perk, engi perk (which are already applied to the base unit) and the hack ability are just on top, just to have it.

Hence I think that your change would unbalance the units instead of balancing them more.

**Review by Bob-Murphy — CHANGES_REQUESTED** [review]
As you can see every unit has some traits increased and others decreased. This was done to differentiate from one another whilst keeping them balanced.
This chance would kinda break it as it would give the riflemen only positive changes.

TL - 0,8+0,8+1,4 = 3
Riflemen - 0,8+0,8+1 = 2,6 (was at 2,8 before your change so was already overall better than other units)
GL - 1,2+0,8+1 = 3
AR - 1,2+0,8+1 = 3
Engi - 1+1+1 = 3
Medic - 1+1+1 = 3

The extra abilities like medic perk, engi perk (which are already applied to the base unit) and the hack ability are just on top.

Hence I think that your change would unbalance the units instead of balancing them more.

If you want riflemen to carry more, set audible and camo to 0,9 so it stays at the sum of 2,8 so it stays somewhat balanced.

**Comment by sevenjames** [comment]
Bob, I think you may have grabbed the wrong rifleman numbers. 

I quadruple checked the current values and constructed this evaluation:

```
                Current Unit Trait Coef Values         R Suggestions
                Cmd  Med  Eng  TL   AR   GL   R        R-a  R-b
audibleCoef     0.8  1.0  1.0  0.8  1.2  1.0  0.8      0.8  0.9
camouflageCoef  0.8  1.0  1.0  0.8  1.0  1.2  1.0      1.0  0.9
loadCoef        1.4  1.0  1.0  1.4  0.8  0.8  1.2      1.0  1.0
===============================================================
Sum of Coefs    3.0  3.0  3.0  3.0  3.0  3.0  3.0      2.8  2.8
```

R-a: Remove load penalty only. This PR.
R-b: Remove load penalty and balance audible and camo. Bob's suggestion.

Summary Points:

1. For all Coef values, lower is better.

1. Unit traits are currently balanced. All units have a trait Coef sum of 3.

1. a. Both suggested adjustments to rifleman result in the same trait Coef sum of 2.8 
   b. making it the only role with a trait Coef sum less than 3
   c. making it very slightly better than the other three non-skilled roles.

Personally, I like the combined suggestion of 0.9 audible + 0.9 camo + 1.0 load because it makes the rifleman more balanced within itself which corresponds to the idea of a rifleman being an "average soldier" with no particular strength or weakness, while simultaneously giving them a slight edge to compensate for having no effective special skill.

Expanded evaluation that includes skill scoring:
https://docs.google.com/spreadsheets/d/e/2PACX-1vRn9l_XjgKL-T391VBoM_BavZHSCGKYDdG2kkjCTc2OvHl_StNgHxrWx31b9HjYVgXEk97gtrJsBxne/pubhtml?gid=2139457957&single=true

**Comment by Bob-Murphy** [comment]
I indeed must have slipped in a line somewhere, good catch!

In this case I also have to adapt my recommendation in regards that a change should not unbalance the units to the following:
--> If you want riflemen to carry more, set all values (audible, camo and carry capacity) to 1.0 so it stays balanced at 3.0.
The "hack drone" still is an additional feature that has no impact on the balance. It's simply a job the unit can do.

The suggestion that you derived from my incorrect statement also would unbalance the rifleman from 3.0 to 2.8 - in either of the 2 possible adjustments.
Also I do not think that there is a need to "compensate for having no effective special skill".
As I stated before, I do not consider the additional perks when it comes to the balance.
Because when I would do so, we would have to downgrade the medics, the engineers as well as heavily the commander for having the perks, which would make it unnecessarily harder for Singleplayers.

Sidenote:
I really appreciate the nice spreadsheet. I like shit like that!

**Comment by sevenjames** [comment]
I support the change of all three rifleman coef values to 1.0.

The full set of roles would also attain fresh balance:
- three roles with special skills and balanced stats (med, eng, rifle)
- three roles with special stats and no skills (teamlead, ar, gl)
- one special case (commander)

**Comment by Bob-Murphy** [comment]
Adapted manually as PR is broken due to deleted branch.
https://github.com/official-antistasi-community/A3-Antistasi/commit/7b6ddb2c71f74fced7de3ecbde4dd508eacf9b6f

**Pull request closed without merging**
