### PR TITLE
Updated Logging for Verbose layer

### LINKED ISSUE #864: Look at moving the Performance logging to the standard method.
Look at moving the Performance logging to the standard method.

### PR DESCRIPTION
**Pull request by Toakan**
## What type of PR is this.
1. [ ] Bug
2. [X] Enhancement

### What have you changed and why?
Information:

I've updated `fn_log` with a some examples in the header of the file on how to use the actual function as someone on the team requested.

Further #895, I have changed the following to make use of the Verbosity log level now that it's implemented. Logs attached to show them working.

- fn_equipRebel
- fn_NATOCrate
- fn_CSATCrate

[CrateAndRebel.log](https://github.com/official-antistasi-community/A3-Antistasi/files/4394319/CrateAndRebel.log)

I have also closed #864 as part of this since it was just a log change ~this needs one additional change first.~

[864-LogExample.log](https://github.com/official-antistasi-community/A3-Antistasi/files/4394301/864-LogExample.log)

### Please specify which Issue this PR Resolves.
closes #864 

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the Mission in Singleplayer?
2. [X] Have you loaded the Mission in a Dedicated Server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

********************************************************
Notes:

~I need to make the logPerformance Server only, which i'll do in another commit. Then i'll remove the Don't Merge and wait for review.~

### CODE REVIEW

**Comment by Bob-Murphy** [comment]
why don't merge?

**Comment by Toakan** [comment]
Read the Notes: @Bob-Murphy ...

**Comment by Bob-Murphy** [comment]
I'm a spoon

**Comment by Toakan** [comment]
Looks like this is called on startup by the initServer, no clients call it at all so I'm in the clear here. @Bob-Murphy

**Pull request merged**
