### PR TITLE
Fix typo in initZones

### LINKED ISSUE #695: Town road setup bug
*Version:* 2.2
*Mods:* Any
*Environment*: Tanoa/Altis/CherSum specific.

***Issue:***
Typo introduced to fn_initZones.sqf in 2e2d7f7c34652280dc708f1eab9dfb51a9b8faf8 causes massive RPT spam and probably breaks stuff. Sample error:

```
1:12:40 Error in expression <] ) then
{
_roads = roadsX getVariable [_name, []];
if (count _roads == 0) then >
 1:12:40   Error position: <_name, []];
if (count _roads == 0) then >
 1:12:40   Error Undefined variable in expression: _name
 1:12:40 File functions\init\fn_initZones.sqf [A3A_fnc_initZones]..., line 81
```

### PR DESCRIPTION
**Pull request by jaj22**
## What type of PR is this.
1. [X] Bug
2. [ ] Enhancement

### What have you changed and why?
Fixed clear typo added in 2e2d7f7c34652280dc708f1eab9dfb51a9b8faf8.  

### Please specify which Issue this PR Resolves.
closes #695

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

### CODE REVIEW

**Comment by wurzel0701** [comment]
#670 has this fix too, not sure how to handle this properly

**Comment by jaj22** [comment]
Needs merging ASAP, so it can't wait for #670. As the changes to those lines are identical, it shouldn't cause any issues with #670. I believe Git handles that case silently.

**Comment by wurzel0701** [comment]
If thats the case it should be fine, strange thing, my test never run into any error messages from it, just weird logs

**Comment by jaj22** [comment]
It'll only cause actual errors on Tanoa. `_name` is defined by unrelated code on Altis and Chernarus, so it would have odd (and potentially permanent) effects on those maps but won't throw. An example of why variables should be scope-constrained.

**Pull request merged**
