### PR TITLE
Move Solnichniy outpost to where the radio tower is

### PR DESCRIPTION
**Pull request by rurku**
## What type of PR is this.
1. [x] Bug
2. [ ] Enhancement

### What have you changed and why?
Information:
For some reason this outpost was moved closer to the main road, but this is a radio tower outpost so needs to be on the hill where the tower is.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the Mission in Singleplayer?
2. [ ] Have you loaded the Mission in a Dedicated Server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

********************************************************
Notes:

### CODE REVIEW

**Comment by Bob-Murphy** [comment]
I will look at it shortly.

**Comment by Bob-Murphy** [comment]
@rurku 
First of all thank you for the pull request.
Now to the topic:
I won't merge your PR as I have intentionally moved some outposts on Chernarus summer as a lot of outposts where only a flag in the middle of nothing without any fortifications, buildings and so on.
The outpost_13 now is located in the nearby village/town in a distance of approx 550m.
Besides that your PR was incomplete as we have now added new additional markers to outposts. In this case it's the marker outp_13_vehicle which is automatically spawning the vehicles which are available at this outposts. Some other outposts even have helipads and/or mortars now.

Also, not every radiotower needs to be within a military zone. It makes things repetitive if there always are the same things ;)

image
image

So thank you very much again and best regards.
Bob

**Comment by rurku** [comment]
@Bob-Murphy Thank you for having a look at it and the explanation!
On Chernarus in 2.1.2 all radio towers either had an outpost near them or were removed from the map (in initZones.sqf) so I assumed that was the author's intention :)

Unguarded towers might have some unintended consequences though. I haven't tested it but I think that putting an observation post or roadblock near an unguarded radio tower might result in that tower broadcasting your propaganda and winning support in nearby towns.
That might have been intentional, but I don't think so, judging by how it's coded.

**Comment by Bob-Murphy** [comment]
No need to thank me.
If there is something regarding maps I look at it and it's just my style to be honest. Imagine I simply would have written NO and closed it. I appreciate your input and therefore think that an honest answer is the least I can do.

Regarding Antistasi - yes you are right. In the past every outpost was either within the boundaries of a military installation or removed via code. In my eyes that makes the mission more predictable and streamlined. Therefore I tried to break up the static pattern a little bit. I even have added new outposts to old maps, moved roadblocks (because everybody knows them all) and stuff like that.

By the way, are you already on our discord? You maybe get a slightly better feeling about what we do and why when you read through a few channels.

**Comment by rurku** [comment]
Yes I found your discord, thanks :)

**Pull request closed without merging**
