### PR TITLE
issue 1590 fix - delete prop from vehicle arrays

### LINKED ISSUE #1590: Servicing container props in 3CB vehicle arrays
**Describe the bug**
The prop "UK3CB_BAF_MAN_HX60_Container_Servicing_Air" is in the vehNATOLightUnarmed array of 3 3CB templates

**To Reproduce**
look at the code

**Expected behaviour**
not have a container spawn instead of a car

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Bob-Murphy**
removes the prop "UK3CB_BAF_MAN_HX60_Container_Servicing_Air" from three vehicle template arrays

## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information: because prop != vehicle
    

### Please specify which Issue this PR Resolves.
closes #1590

### CODE REVIEW

**Review by Lazejun — APPROVED** [review]
Not the trusty Attack containers D:

They are kinda dumb in there, Meer wanted them to apear so i was told to NOT remove them,
You can put them in the Combined Array which spawns at Airbases, if you want them to Apear.
https://github.com/official-antistasi-community/A3-Antistasi/blob/7ce88ae233ed1e3f528a0a9a49d7cd4151ae12ae/A3-Antistasi/Templates/3CB_Occ_BAF_Arctic.sqf#L156
-----> Apparently you can rearm the AH64s without them but eh, i dont realy care

**Comment by Bob-Murphy** [comment]
Having a container spawn when a vehicle with crew should spawn is nonsense.
Will stay out.
If we really want them to spawn in the future, it would be completely separated from vehicle arrays.

**Comment by CalebSerafin** [comment]
> -----> Apparently you can't rearm the AH64s without them <br/>

Then could we swap them out with RHS Apaches? Unless 3CB imposes that restriction on them as well.

**Comment by Lazejun** [comment]
But Default Crew, cause thats still a thing, USAF Pilots < Bri'ish Pilots.

Regardless most players wouldnt even know that you "Need" the Dumb containers. i don't care enough to look if thats actually a thing cause you should be able to use Ammotrucks/ If its the inventory Ammo joke of 3CB BAF you can get the Ammo from the Arsenal

**Pull request merged**
