### PR TITLE
Fix non-pylons being removed by prepPylons

### LINKED ISSUE #2246: [Bug]: Ghost Hawk door guns break when taken from the garage
### Describe the bug

When a UH-80 Ghost Hawk is taken out of the garage, the door miniguns are visually present and can be mounted, but Arma acts as though they're not weapons: They cannot be fired, and the top-right UI is blank.

May apply to other similar vehicles. I haven't checked. I'm guessing it's related to the pylon code.

Tested hosted, pure vanilla and CBA+ACE. Both legitimately acquired and Zeus'd UH-80s. Had an ammo source. Haven't tested more recent versions than 2.5.3 so let me know if this code changed recently.

### How to reproduce

Get an airport, zeus in a UH-80 (empty vehicles, NATO), garage it, pull it out, mount one of the miniguns.

### Version

2.5.3

### Have you altered the code?

No

### What i have changed

_No response_

### Map

Doesn't matter

### What server?

LAN Hosted

### Time bug occured (Server time/UTC)

_No response_

### Mods

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jaj22**
### What type of PR is this.
1. [X] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Fixed a bug where the garage's pylon-removal code could remove weapons that were not pylons due to them sharing magazines with pylon weapons. The new code should work correctly with everything but I haven't tested it with much.

Also fixed a zero-divisor bug in the ammo percentage calculation that I ran into with the FA-181.

### Please specify which Issue this PR Resolves.
closes #2246

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

Should ideally be tested with a decent selection of vehicles. I've only tried a few vanilla air vehicles so far.

### How can the changes be tested?
Enable debug mode to get TRACE working. Take vehicles out of garage and check the output of `HR_GRG_fnc_prepPylons | Removing pylon weapons:`.

### CODE REVIEW

**Review by HakonRydland — APPROVED** [review]
lgtm

**Review by Lazejun — APPROVED** [review]
Checked the known Cases that broke, they don't get their Weapons removed anymore.

**Comment by jaj22** [comment]
Out of scope but I'll take a quick look.

**Comment by jaj22** [comment]
Well, it's the get that's the problem rather than the set. Third parameter here on the pylons is the turret path ([] not [-1] for pilot because some BIS shit is busted):
```
[
[false,["168Rnd_CMFlare_Chaff_Magazine",[-1],168]],
[false,["CUP_1200Rnd_TE1_Red_Tracer_30x113mm_M789_HEDP_M",[0],1200]],
[false,["Laserbatteries",[0],1]],
[true,[1,"pylonLeft1",[0],"CUP_PylonPod_19Rnd_Rocket_FFAR_M",19]],
[true,[2,"pylonLeft2",[0],"CUP_PylonPod_4Rnd_AGM114K_Hellfire_II_M",4]],
[true,[3,"pylonRight1",[],"CUP_PylonPod_4Rnd_AGM114K_Hellfire_II_M",4]],
[true,[4,"pylonRight2",[0],"CUP_PylonPod_19Rnd_Rocket_FFAR_M",19]],
[true,[5,"pylonWingL",[0],"CUP_PylonPod_1Rnd_AIM_9L_Sidewinder_M",1]],
[true,[6,"pylonWingR",[],"CUP_PylonPod_1Rnd_AIM_9L_Sidewinder_M",1]]]
```

**Comment by jaj22** [comment]
Four hours later, fix off-by-one error.

In general there's a lot of magazine-based detection here that's making risky assumptions. Not sure why, given that pylons seem to have turret data in config. getPylonTurret actually uses it as a fallback, except with incorrect output translation.

Doesn't help for figuring this shit out that config viewer dumps me into config root whenever I try to expand components or turrets for most vehicles. Don't know what that's about.

**Pull request merged**
