### PR TITLE
readded debug functions second time

### PR DESCRIPTION
**Pull request by targetingsnake**
## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    

### Please specify which Issue this PR Resolves.
#3130 

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host? (in the last version i added it)
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

details can be found in #3130 

********************************************************
Notes:
Please never squash commits if there is a branch based on them

# OLD PR:

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
Adds ability so spawn units of current selected template as well as fitting vehicles

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

1. Load into Antistasi
2. Start game with selected Factions
3. execute locally while in large area without Obstacles (Salt sea on Altis) and check if vehicle Spawner spawns every template vehicle with

`[] call A3A_fnc_debugSpawnVics;`

for the unit-spawner use: `[] call A3A_fnc_spawnSelectedTemplateAI;`

********************************************************
Notes:

These Script are only build for debuging

### CODE REVIEW

**Review by Bob-Murphy — CHANGES_REQUESTED** [review]
Please add a debug line or maybe even a hint at the end of both script to confirm that spawning has completed.
Just so we know that everything ran to 100%.

**Comment by targetingsnake** [comment]
@Bob-Murphy Additional Debug output added as Info (functions only be triggered manual, should also be visible if people forget to turn on debug or verbose log level)

**Review by Bob-Murphy — APPROVED** [review]

**Comment by targetingsnake** [comment]
if wanted i could add a zeus module for this functions which is only available when arma is in debug mode

**Review by killerswin2 — APPROVED** [review]

**Comment by killerswin2** [comment]
https://tenor.com/view/monkey-look-the-other-way-look-away-awkward-weird-gif-17246188

**Review by jaj22 — APPROVED** [review]
Fuck it.

**Pull request merged**
