### PR TITLE
Fix typo in deleteSave, add new saved vars

### LINKED ISSUE #1474: Typo in functions/save/fn_deleteSave.sqf omitted underscore for postfix .
**Describe the bug**
The underscore for postfix has been omitted.
https://github.com/official-antistasi-community/A3-Antistasi/blob/eb9da4dcb1ace3779aefe703acdbe56b4c8b9426/A3-Antistasi/functions/Save/fn_deleteSave.sqf#L15
This currently requires a bit of a hack-patch to work.

**To Reproduce**
Try use A3A_fnc_deleteSave without patching postfix as a global variable on the server.
This will throw a runtime error as `postfix` is undefined.

**Expected behaviour**
`postfix` is changed to `_postfix` and A3A_fnc_deleteSave  does not crash with valid inputs.

**Environment (please complete the following information):**
Version: July `22ba068 on May 31` => 2.3.1 `eb9da4d on September 15 `
Map (specify if Altis Blufor): 

[x] LAN Hosted
[x] Private dedicated server
[ ] Private dedicated server with Headless client(s)
[ ] Community Server 1
[ ] Community Server 2
[ ] Community Test Server
[ ] Community Test Server 2

Mod-set: Any will do

### PR DESCRIPTION
**Pull request by jaj22**
## What type of PR is this.
1. [X] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Fix typo in deleteSave that probably slipped through due to excessive debug console testing. Also added the new saved variables for deletion.

### Please specify which Issue this PR Resolves.
closes #1474

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

### CODE REVIEW

**Review by CalebSerafin — CHANGES_REQUESTED** [review]
The main bug has been fixed and some more variables added.
However, it appears that some variables may slip through.

The following lists are found in `Save/fn_loadStat.sqf:`

### These are commented out in the header:

- weaponsPlayer
- magazinesPlayer
- backpackPlayer
- mrkNATO
- prestigeNATO
- prestigeCSAT
- planesAAFcurrent
- helisAAFcurrent
- APCAAFcurrent
- tanksAAFcurrent
- armas
- items
- backpcks
- ammunition
- WitemsPlayer
- resourcesAAF

### These are not commented out:

- testingTimerIsActive
- ammunition
- backpcks
- items
- armas
- prestigeCSAT
- prestigeNATO
- mrkNATO

### These have been discovered in the clean-slate test
- testingTimerIsActive

* [ ] The commented out variables are hit and miss, some of them don't exist and some exist elsewhere in the code. However, in a quick clean slate test, the only one that showed through is `testingTimerIsActive`.

* [ ] Although it appears that the tool looks for saved players, a `savedplayers3505311124antistasistratis` entry containing the Steam-64-UID and an empty array was left behind.

* [ ] `antistasisavedgames` was left with an empty array, could it be possible to check if no other missions are saved and nil this?

### The non-binarised test vars data is provided below:

> 1) A new profile created > new game > load in > save
> 2) Load Game > Run tool > exit


[Antistasi Statis Clean Vars.cpp.txt](https://github.com/official-antistasi-community/A3-Antistasi/files/5255837/Antistasi.Statis.Clean.Vars.cpp.txt)
[Antistasi Statis Clean Remaining Vars.cpp.txt](https://github.com/official-antistasi-community/A3-Antistasi/files/5255838/Antistasi.Statis.Clean.Remaining.Vars.cpp.txt)

**Comment by jaj22** [comment]
This was only designed to handle community version savegames (otherwise there are a ton of translated vars, and I think serverID/campaignID compatibility problems), so I think most of those are out of scope.

However the following are oversights:

- testingTimerIsActive. Missed this one being added. Not sure what it's for, but whatever.
- savedPlayers. Recursive scanning failure.
- prestigeNATO and prestigeCSAT. These are the pre-2.3 aggro values, should have been saved for backwards compatibility but aren't. Worse than a deleteSave issue.

loadStat has some ancient entries that should probably be cleared out at some point.

I'm inclined to leave antistasiSavedGames as an empty array on clearance.

**Comment by Bob-Murphy** [comment]
testingTimerIsActive is part of @wurzel0701 code that can track the amount of manhours on the server even after a server restart (IIRC).

**Comment by jaj22** [comment]
Added the vars I think are within scope. 

On second thoughts it's ok not to save to the old aggro values as they have defaults in initVar and aren't really convertible with the new aggro. In general I'd like to preserve the ability to load current saves in the previous version where possible, in case we release something with a bad bug that doesn't show up until halfway through the mission, but loading with an aggro reset is acceptable.

**Review by CalebSerafin — APPROVED** [review]
Changes are good and effective.

**Pull request merged**
