### PR TITLE
add expansion info

### LINKED ISSUE #2269: [Feature Request]: Add Expansion Information for Antistasi
### Related problem

Desktop Screenshot 2022 02 19 - 14 01 46 57

### Proposed feature

Desktop Screenshot 2022 02 19 - 14 02 22 54

### Alternative solutions

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Bob-Murphy**
## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
added expansion info
image
    

### Please specify which Issue this PR Resolves.
closes #2269 

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Important:

@HakonRydland we have to ensure that the info from the mod.cpp is properly taken over to the published mod and the .paa has to be in the main folder as well

### CODE REVIEW

**Comment by HakonRydland** [comment]
current setup will copy over the mod.cpp to the build folder so thats fine, im a bit worried about the path for the image as i havent found any info on where it will originate the search and if its the same on all machines, but then this would only be for the clients anyways, finally i have looked in to using CfgMods instead of mod.cpp but im uncertain if that is still functional in arma 3... will have to look into that.

but for now as long as you verified the pathing works then this is ok

**Comment by HakonRydland** [comment]
as a side note we should get a logo as well, maybe the shield?

**Comment by Bob-Murphy** [comment]
I confirmed it working when it's in the same folder as the mod.cpp, the addons and keys folder, same as GRAD has it set up.

**Comment by Bob-Murphy** [comment]
Regarding the Logo, I also was thinking about that.
I got the assets and could do that as well.

**Comment by HakonRydland** [comment]
alright then i will only need to adapt the script, out of curiosity could you put the image in the pictures folder and give it the path `\x\A3A\addons\core\Pictures\antistasi_overview.paa` and see if that works fine too?

**Comment by HakonRydland** [comment]
if so it would offload the work from the build scripts and just be included properly by arma from the pbos

**Comment by jaj22** [comment]
Can we have version numbers both here, in the mission selection list and on the workshop? It's a bit of a disaster for support at the moment, as no-one knows what the hell they're running.

**Comment by HakonRydland** [comment]
the mission selection ones are stringtable entries and so we cant do it unless we manually update each map name for each release, the expansion menu name we could do

**Comment by HakonRydland** [comment]
i should add im making assumptions that the mod.cpp gets pre processed

**Comment by Bob-Murphy** [comment]
done from my end

**Review by HakonRydland — APPROVED** [review]

**Pull request merged**
