### PR TITLE
Templates - Unsung Templates 

### PR DESCRIPTION
**Pull request by stutpip123**
## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    Added Unsung Templates, NVA, US, VC and Civ
    Added Unsung Logistics Nodes
    Changed Detector, Selector and Params to allow loading of templates
    Added Unsung AA Planes to fn_setPlaneLoadout.sqf
### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Running the mission on a server with Unsung the templates will load and play.
Needs checking over for mistakes and issues or missing things, then play testing
********************************************************
Notes:
fn_setPlaneLoadout.sqf needs Unsung CAS Planes adding

### CODE REVIEW

**Comment by CalebSerafin** [comment]
I'll take care of merge conflicts after it is reviewed and approved. Just ping me on Discord.

**Comment by stutpip123** [comment]
whereabouts am I supposed to ping, I've been waiting for instructions on what to change or do next for months

**Comment by Bob-Murphy** [comment]
We are dang busy right now so it might take a while, sorry 'bout that.
When somebody has looked at it, feedback will be here.
It's currently lower priority but certainly not forgotten.

**Comment by stutpip123** [comment]
I assumed you all were. Its not a problem just let me know when there is something to be done

**Comment by Lazejun** [comment]
We will have to see if Frost can Merge into the PR, as you didn't allow Maintainers to Edit the PR.

If he can't you will have to Merge https://github.com/official-antistasi-community/A3-Antistasi/tree/Update-2201-%F0%9F%99%84 into your Branch which should resolve all Conflicts Update to Unstable and fix a few small mistakes here and there.

**Comment by stutpip123** [comment]
allow edits by maintainers is ticked on my end

**Comment by Lazejun** [comment]
Huh, i will try again

**Comment by Lazejun** [comment]
Frost is trying with a PR, check on your Pull Requests and see if that works

**Comment by stutpip123** [comment]
the PR has been merged

**Comment by Bob-Murphy** [comment]
PR got merged by stut

**Comment by Lazejun** [comment]
And it actually solved the Merge conflicts 🥳 

i mostly checked Logistics so far and a few things with Formating etc.

Updated so it works with the new Selction etc. had to rename the files for that too.

In Logistics you did the Funny of using = instead of Append resulting in me loosing my mind for a while as the = just kills all previous Logistic entries and only sets what was in Unsung Nodes.

Also Adding the Nodes to Helicopters is interesting but they are neither a Car or a Boat.

https://github.com/official-antistasi-community/A3-Antistasi/blob/d40c2c8298dab96a86500fd8ef6fc870d7d6b62d/A3A/addons/core/functions/Logistics/functions/fn_logistics_tryLoad.sqf#L26-L28

I will see when i get around checking the rest.

Also if you want to test/Check your stuff you have to build the Mod now and load it to use the Missions, here is one Guide.

https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/How%20to%20build.md

**Comment by stutpip123** [comment]
Having never used Visual Studio all the instructions on "how to build" make no sense to me. I've never made or worked on an arma 3 mod, only missions

**Comment by Bob-Murphy** [comment]
@Lazejun had any chance to look at it again?
Also MeRgE cOnFlIcTs again.

**Comment by Lazejun** [comment]
> @Lazejun had any chance to look at it again? Also MeRgE cOnFlIcTs again.

It's a bitch to work with due to the way it's forked, I will redo the PR and Co Author Stutpip so Credit isn't lost.

I was kinda waiting on feedback/awnser to the previous question.

Like the Logistics nodes include Helis but Helis are not recognised by Logistics, but it could be a nice feature as most Helis could carry a minimum of 1 Node ---> Loot box

**Comment by Bob-Murphy** [comment]
I have no objection to add helis to the list.
If it fits, it sits.

**Comment by Lazejun** [comment]
This PR continues in #2379

**Pull request closed without merging**
