### PR TITLE
Phase 1 of mod integration safety work.

### LINKED ISSUE #1266: Reformat Templates folder
Phase 1 of Bob's request to pull mod integration stuff out of core files where inadvertent damage could be done.

This will be a major restructure of the template folder consisting of moving everything into sub-folders sorted by mod for major implementations, and category for smaller ones.

### PR DESCRIPTION
**Pull request by SonorousMeerkat**
## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    Re-formats the Template folder to make it more organised and readable.
    Updates file paths for selector.sqf
    Updates file call for the PvP loadout funtion.
    Updates the template guide txt
    Adds full set of example templates for integrator to read.

### Please specify which Issue this PR Resolves.
closes #1266 

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in singleplayer?
2. [x] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
    Load all modsets on 1 of each environment of map, make sure that *all* pvp loadouts load properly and that the correct template is loaded and used.
********************************************************
Notes:
  This was the 2nd easiest part.

### CODE REVIEW

**Comment by SonorousMeerkat** [comment]
Testing completed, PvP not checked due to not having a #2 but there are no errors anymore.

**Review by jaj22 — APPROVED** [review]
Changes look straightforward enough, but apparently git is too dumb to resolve a merge conflict where one commit moved a file and other commits changed it.

**Comment by Lazejun** [comment]
well yes/no, it hasnt been Updated yet 👀, same as Most PRs rn that are directed at Unstable :D

**Comment by SonorousMeerkat** [comment]
Apologies for not seeing this, If this conflict still exists i'll need to see or be told it. I see nothing on my end.

**Comment by CalebSerafin** [comment]
@Bob-Murphy Ready for merge.

**Pull request merged**
