### PR TITLE
Gm templates desert prep

### LINKED ISSUE #2761: Additional GM vehicle logistics
Try if the following spaces are suitable for holding a loot/surrender crate:
Trunk of `gm_gc_civ_p601`
Trunk of `gm_gc_army_uaz469_cargo`
Trunk of `gm_ge_civ_w123`

### LINKED ISSUE #3096: [Bug]: Name of GM; Nationale Volksarmee too long to display climate designation
### Describe the bug

In the selection menu to choose the faction the climate designation for the nationale Volksarmee from GM is currently not really readable.

### How to reproduce

Load Arma 3 with Antistasi and all required mods to start a game with GM-Templates. Start new game, select factions.

### Version

3.x

### Have you altered the code?

No

### What i have changed

_No response_

### Map

every

### What server?

LAN Hosted, Private dedicated server, Private dedicated server with Headless client(s)

### Time bug occured (Server time/UTC)

_No response_

### Mods

```html
Gm, CUP-Modset
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by targetingsnake**
## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:

This template should make use of the desert vehicles of GM BW-faction and if there are any also of the NVA ones.
also closes #3096 
also closes #2761 

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

load template and play campaign

********************************************************
Notes:

### CODE REVIEW

**Comment by targetingsnake** [comment]
if someone has an idea what i can use for GM BW milita as desert uniforms i'm up for it, they currently use the standard olive ones

**Comment by targetingsnake** [comment]
after spoke with @killerswin2 i think oliv BW militia is okay for desert template

**Comment by targetingsnake** [comment]
Changes:

- new Desert Templates for GM BW and GM NVA
  - Vehicles in desert camo for both parties where possible
  - other uniforms for enemies where possible
  - other guns (camo wise) where possible
- Fixed Mag issues in all GM-Templates
- added CUP-Rebel Uniforms to GM-Rebel template

Still open:
#2761

**Comment by targetingsnake** [comment]
Changes:

- new Desert Templates for GM BW and GM NVA
  - Vehicles in desert camo for both parties where possible
  - other uniforms for enemies where possible
  - other guns (camo wise) where possible
- Fixed Mag issues in all GM-Templates
- added CUP-Rebel Uniforms to GM-Rebel template
- added more logistics nodes to GM vehicles ( #2761 )

**Review by Bob-Murphy — APPROVED** [review]
Tested, no errors and looks good.

**Review by Bob-Murphy — APPROVED** [review]
Tested, no errors and looks good.

**Pull request merged**
