### PR TITLE
Meer MIE phase 7 (UNSUNG)

### PR DESCRIPTION
**Pull request by SonorousMeerkat**
## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    Integrates UNSUNG as a supported mod.

### Please specify which Issue this PR Resolves.
closes none

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in singleplayer?
2. [x] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
  Load the mission with UNSUNG enabled. Any map as it is exempt from environment checking on account of not having any alternative camo.
********************************************************
Notes:

### CODE REVIEW

**Comment by Glloyd** [comment]
Played a couple hours of this tonight with a small group. Only notable issue was a US attack triggering and nothing seemed to happen. Planes also didn't appear to spawn at the airfield, but that could be because we were at War Level 1. Also it's strange that the armed MULEs are used for roadblocks instead of the armed MUTTs. Will let you know if we come across any further issues in the future.

**Comment by SonorousMeerkat** [comment]
Known problems with some vehicles, the cause of both issues, but due to an upcoming system slated for the same release as this it will not be changed here.

**Comment by Glloyd** [comment]
Thanks for letting me know. Out of curiosity, is there anything I can do in the meantime as a temporary way to address the issue?

**Comment by SonorousMeerkat** [comment]
Remove the MULEs from the template. Might not fix all problems but the MUTTs should be better all round.

**Comment by Glloyd** [comment]
Thanks for the suggestion! I'll give it a shot.

**Comment by SonorousMeerkat** [comment]
Due to plans for new template system, this PR is no longer going to be worked on.

**Pull request closed without merging**
