### PR TITLE
Silence Players with Ace / Missed Semicolon

### PR DESCRIPTION
**Pull request by Lazejun**
## What type of PR is this.
1. [x] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
Added a Check for not having Ace, so Players with Ace won't get a Speaker set and it should stay with "Ace_novoice".
Removed the Speaker Lines in OnPlayerRespawn.
Added a missed Semicolon.

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

### CODE REVIEW

**Comment by jaj22** [comment]
What's actually going on here? Were there any intentional feature changes to player voice behaviour, or is it just that the new code was unintentionally overriding something ACE was doing to silence players?

**Comment by Lazejun** [comment]
> What's actually going on here? Were there any intentional feature changes to player voice behaviour, or is it just that the new code was unintentionally overriding something ACE was doing to silence players?

The Goal was to set the Player voice to the same as Ai Voice, the problem is that AceNoRadioEnabled apparently looses against SetIdentity on a Server. So you cannot just Mute it by turning on the Setting.

Most Players using Ace dont even know that their Players can have a voice so thats a Suprise for Most too.

Checking for the setting didnt realy work when i tried as it Errord with Vanilla, so i removed it as it worked as expected on Local host, but not a on Dedicated Server.

--------> Most Players using Ace don't care about their Character having a Voice/It can be annyoing with TFAR/ACRE so this Quick fix was supposed to just disable it if Players use Ace.

**Comment by Lazejun** [comment]
[](https://github.com/official-antistasi-community/A3-Antistasi/pull/2326/commits/b1584cfd3dda2033d7b40b626842641e90fe7c92)[b1584cf](https://github.com/official-antistasi-community/A3-Antistasi/pull/2326/commits/b1584cfd3dda2033d7b40b626842641e90fe7c92)
Now this has a Check for Ace, then a Check for the Setting so it will not Error for Vanilla,
If Players turn of ace_noradio_enabled then they get a Voice set and if they don't use ace they get a Voice.

**Comment by jaj22** [comment]
I expect you could just do:
```
if (isNil "ace_radio_enabled" or {!ace_radio_enabled}) then {
    [player, nil, selectRandom (A3A_faction_reb get "voices")] call BIS_fnc_setIdentity
};
```
What's the idea of the onPlayerRespawn change though? Was that code not necessary in vanilla?

**Comment by Lazejun** [comment]
> I expect you could just do:
> 
> ```
> if (isNil "ace_radio_enabled" or {!ace_radio_enabled}) then {
>     [player, nil, selectRandom (A3A_faction_reb get "voices")] call BIS_fnc_setIdentity
> };

Yeah thanks that is a lot better, will try in a sec.

> What's the idea of the onPlayerRespawn change though? Was that code not necessary in vanilla?

I assumed that the Voice would need to be set again on Respawn, but my Testing on Local host/TADST showed that you actually keep the Voice set by SetIdentity.

**Pull request merged**
