### PR TITLE
Add Another Option For Civilian Traffic

### LINKED ISSUE #339: Add another option for civilian traffic
Add an option to disable the civilian traffic and set it to zero on the parameter.

### PR DESCRIPTION
**Pull request by Godlikehobbit**
## What type of PR is this.
1. [ ] Bug
2. [x] Enhancement

### What have you changed and why?
Information:
Added the ability to disable civilian traffic via a mission parameter

Also saw that there were a couple errors about Tool kits when testing. Found out that JNA had a typo for a couple references to ToolKit as because for some reason the K is capitalized in ToolKit but not Medikit
### Please specify which Issue this PR Resolves.
Closes #339 

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the Mission in Singleplayer?
2. [x] Have you loaded the Mission in a Dedicated Server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

********************************************************
Notes:
As far as I could see the only reference to civTraffic was: https://github.com/official-antistasi-community/A3-Antistasi/blob/c9662602ad2cb2a510abf6c80149bf27bab58362/A3-Antistasi/CREATE/createCIV.sqf#L39 Unless I'm missing something obvious this should be all that's needed.

### CODE REVIEW

**Comment by PoweredByPot** [comment]
Did you by any chance check to see if the 0.5 setting actually functions? We recently had to redo the difficulty math because we also used 0.5 as an option. Turns out it could only handle whole numbers, and I assume that was a limitation of description.ext

If not its no big deal, its likely always been broken, and wont take but ten second to remove.

**Comment by Godlikehobbit** [comment]
I wasn't sure what _numVeh ended up being but from the "math" I did to validate it, 0.5 works

**Comment by PoweredByPot** [comment]
yeah, the only real way to tell is to launch a dedicated server with the parameter set to 0.5.

When you are in the lobby on the DS, open the parameters and see what the value is for Civ Traffic. I'm willing to bet when set to 0.5, it will be blank, meaning it defaults.

If that is the case, just remove the 0.5 option from the description.ext's

**Comment by Godlikehobbit** [comment]
I tested with the civPerc at 35 and it seemed that 0.5 and 1 both resulted in a value less than 1

**Comment by Godlikehobbit** [comment]
Oh nevermind, I see what you're saying, yeah if the number isn't whole it defaults to 1

**Pull request merged**
