### PR TITLE
Templates - Create new Faction Example AdvanceFactionExample.sqf

### PR DESCRIPTION
**Pull request by killerswin2**
## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    Changed the Faction example to a more feature rich example.
Added the sl hats and rifles and moved the launchers to the specific loadout.

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

### CODE REVIEW

**Review by Lazejun — COMMENTED** [review]
This is not needed,

The Example should be the most Basic Variant, not one of the most Advanced one.
If you look at Vanilla there are not even Class Specific Vests, the amount of Uniforms is very low and Weapons are limited.

If People need Examples how to overcome limitations by Modsets they can always look at existing Templates and take ideas and solutions from there.

**Comment by killerswin2** [comment]
Would you take a middle ground? Add this file as an advanced example and leave the factionexample the same as it is now? I.e. I make a new file called factionAdvanceExample. Totally fine with closing this. Wanted to add / change the example because it was inconvenient to switch back to any already fill template to look through it to find small pieces of info.

**Comment by Lazejun** [comment]
That could probably work

**Review by Lazejun — CHANGES_REQUESTED** [review]
Both are the same.

You lost your D in the word Advanced.

There is no point in adding the "longRangeRadios" as they are unused, they add nothing to the Gameplay and they are just heavier Backpacks with that can carry less.

and you lost a Space there in both.
https://github.com/official-antistasi-community/A3-Antistasi/blob/4480b3c6e61adddac331b80637f35e2b443b1fe3/A3-Antistasi/Templates/Templates/%23Examples/AdvanceFactionExample.sqf#L40

**Pull request closed without merging**
