### PR TITLE
Rename AAFKilledEH to rebelUnitKillEH

### PR DESCRIPTION
**Pull request by PoweredByPot**
also renamed poorly descriptive local variable names

### CODE REVIEW

**Comment by PoweredByPot** [comment]
I thought rebelUnit**Kill**EH was good because it wasn't **_Killed_**, and the only reason enemy AI units should be dying in a way that matters is when rebels kill them.

**Comment by Spoffy** [comment]
I see your point, but it's not an event that fires when rebel units kill. For example, they might kill a civilian. Or a rabbit. Or a friendly.

**Comment by PoweredByPot** [comment]
aiUnitKilledEH?

**Comment by Spoffy** [comment]
I proposed a couple above. occupantsInvadersKilledEH is the one I prefer, because it's pretty damn clear.

**Comment by PoweredByPot** [comment]
fixed

**Pull request merged**
