### PR TITLE
Update Stringtable.xml

### PR DESCRIPTION
**Pull request by teemo0803**
Chinese Simplify Trans

### CODE REVIEW

**Comment by teemo0803** [comment]
ALL DONE. PLEAZE MERGE

**Comment by teemo0803** [comment]
HI,I've noticed that many strings were not added in the stringtable yet

**Comment by teemo0803** [comment]
image

In briefing

**Comment by Toakan** [comment]
> 
> 
> image
> 
> In briefing

The reason they have stayed, is because `player createDiaryRecord [Localize "$str_example"` would cause issues from my testing.

For the time being, it was simpler to leave it as is.

**Comment by teemo0803** [comment]
YES I ve reverified this in the game

**Comment by teemo0803** [comment]
## What type of PR is this.
1. [ ]  Bug
2. [x]  Enhancement

### What have you changed and why?
Information:
ADD Chinese Localization


> This is just the groundwork and can be merged in, as it is an external system which is not triggered by the current code at all.
> 
> ### Please specify which Issue this PR Resolves.
> None
> 
> ### Please verify the following and ensure all checks are completed.
> 1. [x]  Have you loaded the Mission in Singleplayer?
> 2. [ ]  Have you loaded the Mission in a Dedicated Server?
> 
### Is further testing or are further changes required?
1. [x]  No
2. [ ]  Yes (Please provide further detail below.)

**Review by Bob-Murphy — APPROVED** [review]

**Comment by Bob-Murphy** [comment]
Manually adapted to 2.3.1 stringtable.
Tested and confirmed working.

**Pull request merged**
