### PR TITLE
CS-1520-FFChecksLocalPvp

### PR DESCRIPTION
**Pull request by CalebSerafin**
## What type of PR is this.
* [x] Bug
* Change
* Enhancement

### Changes
* Inside Punishment_FF: Pvp was previously checked by the "Pvp" variable. However, this variable is not implemented to be JIP compatible.
  * Solution: Pvp is now checked by side group of the _instegator/_victim.

*PS: The brackets will be lined up later for those OCD among us.*

### The big issue that this PR Resolves.
closes [#1520](https://github.com/official-antistasi-community/A3-Antistasi/issues/1520)

### Personal Testing Checks.
2. [x] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
* Yes

## Testing Steps
1. Rebel Shoot Rebel -> Warning & FF Log
2. Rebel Shoot Pvp -> No Notification & PVPHURT log
3. Pvp Shoot Rebel -> No Notification & PVPATTACK log

### Zip of PBO is Provided 
*With Updated/Current Mission SQM*
[Antistasi-TEST-CS-1520-FFChecksLocalPvp-2-3-1.Altis.pbo.zip](https://github.com/official-antistasi-community/A3-Antistasi/files/5323352/Antistasi-TEST-CS-1520-FFChecksLocalPvp-2-3-1.Altis.pbo.zip)

### CODE REVIEW

**Review by HakonRydland — APPROVED** [review]
working, no notification for victim on reb shoot reb case but at least no wrongful punishment

**Comment by CalebSerafin** [comment]
@HakonRydland I assume the warning that the instigator got included that he is admin?

**Comment by CalebSerafin** [comment]
Contain's the issue of WARNINGS not notifying the victim of who hurt them. Fix contained in PR CS-1489-Pun_FFServerSide [#1496](https://github.com/official-antistasi-community/A3-Antistasi/pull/1496). So exclude that.

**Comment by jaj22** [comment]
Should be fine, but one thing I'd like to check here is what happens to group side with various combinations of PvP and rebel players in the same vehicle, as there have been reports of visible side switches.

**Comment by CalebSerafin** [comment]
> Should be fine, but one thing I'd like to check here is what happens to group side with various combinations of PvP and rebel players in the same vehicle, as there have been reports of visible side switches.
That will bug out, then the better solution will be going back to the PvP variable. And making sure it is JIP.

However, in other PR this is made server-side, so if the server has the "pvp" on the player, then the issue might disappear.

**Comment by jaj22** [comment]
I'd go with the side group method as long as there aren't common accidental ways to break it. I'm expecting that the vehicle issue is a misreport or just a visual effect, but it needs testing.

**Pull request merged**
