### PR TITLE
Bob of the day

### LINKED ISSUE #239: Cannot Garrison MG or Mortar Squads
This is caused by a bug when spawning the Unit types. After first creating a Mortar or MG Squad using the Recruit Dialog, they spawn with 94% health.

image

https://github.com/official-antistasi-community/A3-Antistasi/blob/dda9e7ced319f5ffa12f7577c5e236cd112a12f5/A3-Antistasi/dialogs.hpp#L2927-L2946

This issue then leads to the addToGarrison file triggering: 
https://github.com/official-antistasi-community/A3-Antistasi/blob/dda9e7ced319f5ffa12f7577c5e236cd112a12f5/A3-Antistasi/REINF/addToGarrison.sqf#L40-L46

### PR DESCRIPTION
**Pull request by wurzel0701**
Fixes #239, not sure why there was a block at all, so it may lead to unpredicted behaviour

Nothing unusual found in test (Not tested much)

### CODE REVIEW

**Comment by Spoffy** [comment]
One bug this introduces is in line 54 of fn_moveHQ. The code looks for static crewmen in the garrison as a way to count how many mortars there are.

If you manage to add static crewman to the garrison any other way, it'll erroneously think there's another mortar garrisoned there.

**Comment by Spoffy** [comment]
Same in line 97 of fn_createSDKGarrisons. If it sees a static crew member in the garrison, it'll spawn a mortar.

**Comment by wurzel0701** [comment]
The new garrison system will make this easier, I would prefer to stall this till then

**Comment by Bob-Murphy** [comment]
Fine for me.

**Pull request closed without merging**
