### PR TITLE
Documented and changed fn_timingCA.sqf 

### PR DESCRIPTION
**Pull request by shoter**
What type of PR is this.
1. [x] Bug?
2. [x] Enhancement

### What have you changed and why?
First I changed name of variable _timeX into _timeDelta. Easier to understand.
Additionally I documented the whole function so ppl will know what it is doing.

This method very often accepts negative arguments of _timeDelta :
```
	[-1800*_bonus] remoteExec ["A3A_fnc_timingCA",2];
```
The whole if statement inside that method never made sense - that function could never decrease timing of next counter attack. There is a lot of logic in missions containing negative delta so I decided to remove that if statement.

To compensate for that - I changed penalty of difficulty/war level from 400 to 300 per level.    

### Please specify which Issue this PR Resolves.
none
### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the Mission in Singleplayer?
2. [x] Have you loaded the Mission in a Dedicated Server?

### Is further testing or are further changes required?
I do not know.

### CODE REVIEW

**Comment by jaj22** [comment]
I think you missed the point that the <0 check also prevents a negative output when the input is positive. Without it, the results will be even more broken than they were previously.

The current code ignoring the negative inputs (accidentally or otherwise) is arguably a balance positive, given that small player groups are far less able to complete the missions.

**Comment by shoter** [comment]
So it is more likely needed to remove lines of code which are passing negative inputs into that function?

If yes then when I will have free time I will remove those lines of code as they are very misleading.

**Comment by shoter** [comment]
I put back on if statement + reset the value to the old one in the statement I changed.

I removed all places where this method was executed with negative numbers (bc it was doing nothing).

**Comment by Bob-Murphy** [comment]
Hey @shoter 
It seems like this was simply forgotten.
We will revisit this one after publishing the update.
Also, thank you for all the PRs you put forward!

**Comment by shoter** [comment]
This method was already changed in other commit from what I see. I will close this PR.

**Comment by Bob-Murphy** [comment]
Copy that.
Thank you

**Pull request closed without merging**
